In [1]:
import pandas as pd
import numpy as np

Using the Path library to read the file

In [2]:
from pathlib import Path

project_root = Path.cwd().parent.parent
data_path = project_root / "data" / "raw" / "emails.csv"

df_em = pd.read_csv(data_path, header=0)
df_em.head(10)

C:\Users\MadhavGoyal\AppData\Local\Temp\ipykernel_16644\945658655.py:6: DtypeWarning: Columns (0: crm_agent_chase_count, 1: crm_auto_renewal_status) have mixed types. Specify dtype option on import or set low_memory=False.
  df_em = pd.read_csv(data_path, header=0)

,Co_Ref,Time_to_Renewal,crm_accreditation_completed,crm_timely_completion,crm_progress_towards_accreditation,crm_delays_in_accreditation,crm_contractor_suggested_leave,crm_contractor_engagement,crm_contractor_sentiment,crm_contractor_sentiment_score,...,crm_accreditation_issues,crm_membership_overdue,crm_auto_renewal_status,crm_dissatisified_with_renewal_price,crm_customer_complained,crm_refund_mentioned,crm_negative_customer_experience,crm_dissatisfaction_with_support,crm_financial_hardship_mentioned,year
0,KG5766,pre_renewal,Not Discussed,Not Discussed,Not Discussed,Yes,No,Yes,Neutral,50,...,Not Discussed,Yes,0,No,No,Yes,Yes,No,Yes,2025
1,EJ1532,14_out,Not Discussed,Not Discussed,Not Discussed,No,Not Discussed,No,Not Discussed,Not Discussed,...,Not Discussed,Not Discussed,0,Not Discussed,No,Yes,Yes,No,Not Discussed,2025
2,AA4063,prior_year,Not Discussed,Not Discussed,Not Discussed,No,No,Yes,Neutral,50,...,Not Discussed,No,0,No,No,Yes,Yes,Yes,Not Discussed,2025
3,JY9888,prior_year,No,No,Not Discussed,Yes,No,Yes,Satisfied,80,...,Not Discussed,Yes,0,Not Discussed,No,Yes,Yes,No,Not Discussed,2025
4,WO6689,pre_renewal,Not Discussed,Not Discussed,Not Discussed,No,No,Yes,Satisfied,80,...,No,No,0,No,No,Yes,Yes,No,Not Discussed,2026
5,GW7224,14_out,Not Discussed,Not Discussed,Not Discussed,No,Not Discussed,No,Not Discussed,Not Discussed,...,Not Discussed,Not Discussed,0,Not Discussed,No,Yes,Yes,Not Discussed,Not Discussed,2025
6,SB4066,pre_renewal,Not Discussed,Not Discussed,Not Discussed,Yes,No,Yes,Neutral,50,...,Not Discussed,Yes,0,Not Discussed,No,Yes,Yes,No,Not Discussed,2026
7,YK0304,pre_renewal,Not Discussed,Not Discussed,Not Discussed,No,Not Discussed,No,Not Discussed,Not Discussed,...,Not Discussed,Not Discussed,0,Not Discussed,No,Yes,Yes,Yes,Not Discussed,2025
8,HH3570,pre_renewal,Not Discussed,Not Discussed,Not Discussed,No,No,Yes,Satisfied,80,...,Not Discussed,Yes,0,Not Discussed,No,Yes,Yes,No,Not Discussed,2025
9,WZ8475,pre_renewal,Not Discussed,Not Discussed,Not Discussed,No,Not Discussed,No,Not Discussed,Not Discussed,...,Not Discussed,Not Discussed,0,Not Discussed,No,Yes,Yes,Not Discussed,Not Discussed,2025

This dataset contains email interaction data with customers, tracking metrics such as accreditation completion, sentiment, contractor engagement, and various complaints or concerns discussed.
Like the renewal calls, these features will help predict whether customers are at risk of churning after their subscription due date.

In [3]:
df_em.dtypes

Co_Ref                                     str
Time_to_Renewal                            str
crm_accreditation_completed                str
crm_timely_completion                      str
crm_progress_towards_accreditation         str
crm_delays_in_accreditation                str
crm_contractor_suggested_leave             str
crm_contractor_engagement                  str
crm_contractor_sentiment                   str
crm_contractor_sentiment_score             str
crm_dts_or_ssip_mentioned                  str
crm_customer_payment_intention             str
crm_competitors_mentioned                  str
crm_membership_level                       str
crm_platform_issues_raised                 str
crm_agent_chased_contractor                str
crm_agent_chase_count                   object
crm_accreditation_issues                   str
crm_membership_overdue                     str
crm_auto_renewal_status                 object
crm_dissatisified_with_renewal_price       str
crm_customer_complained                    str
crm_refund_mentioned                       str
crm_negative_customer_experience           str
crm_dissatisfaction_with_support           str
crm_financial_hardship_mentioned           str
year                                     int64
dtype: object

In [4]:
df_em.shape

(123389, 27)

Drop columns that are completely null or have unnamed index formats.

In [5]:
# Drop if every value in the column is missing
df_em = df_em.dropna(axis=1, how='all')

# Remove Unnamed columns
df_em = df_em.loc[:, ~df_em.columns.str.contains('^Unnamed')]

print(f"Columns remaining: {df_em.columns.tolist()}")

Columns remaining: ['Co_Ref', 'Time_to_Renewal', 'crm_accreditation_completed', 'crm_timely_completion', 'crm_progress_towards_accreditation', 'crm_delays_in_accreditation', 'crm_contractor_suggested_leave', 'crm_contractor_engagement', 'crm_contractor_sentiment', 'crm_contractor_sentiment_score', 'crm_dts_or_ssip_mentioned', 'crm_customer_payment_intention', 'crm_competitors_mentioned', 'crm_membership_level', 'crm_platform_issues_raised', 'crm_agent_chased_contractor', 'crm_agent_chase_count', 'crm_accreditation_issues', 'crm_membership_overdue', 'crm_auto_renewal_status', 'crm_dissatisified_with_renewal_price', 'crm_customer_complained', 'crm_refund_mentioned', 'crm_negative_customer_experience', 'crm_dissatisfaction_with_support', 'crm_financial_hardship_mentioned', 'year']

Check for null values for every column

In [6]:
print(df_em.isnull().sum())

Co_Ref                                      0
Time_to_Renewal                             0
crm_accreditation_completed             21035
crm_timely_completion                   21035
crm_progress_towards_accreditation      21035
crm_delays_in_accreditation             21035
crm_contractor_suggested_leave          21035
crm_contractor_engagement               21035
crm_contractor_sentiment                21035
crm_contractor_sentiment_score          21035
crm_dts_or_ssip_mentioned               21035
crm_customer_payment_intention          21035
crm_competitors_mentioned               11155
crm_membership_level                    11155
crm_platform_issues_raised              11155
crm_agent_chased_contractor             11155
crm_agent_chase_count                   11155
crm_accreditation_issues                11155
crm_membership_overdue                  11155
crm_auto_renewal_status                 11155
crm_dissatisified_with_renewal_price    11155
crm_customer_complained                 11475
crm_refund_mentioned                    11475
crm_negative_customer_experience        11475
crm_dissatisfaction_with_support        11475
crm_financial_hardship_mentioned        11475
year                                        0
dtype: int64

Checking unique values for each column to understand how the data looks before cleaning

In [7]:
for col in df_em.columns:
    if col not in ['Co_Ref']:
        print(f"\n--- {col} ---")
        print(df_em[col].value_counts(dropna=False).head(10))

--- Time_to_Renewal ---
Time_to_Renewal
prior_year     40022
14_out         32493
45_out         28008
pre_renewal    22866
Name: count, dtype: int64

--- crm_accreditation_completed ---
crm_accreditation_completed
No               46193
Not Discussed    34870
Yes              21291
NaN              21035
Name: count, dtype: int64

--- crm_timely_completion ---
crm_timely_completion
Not Discussed    62517
No               36986
NaN              21035
Yes               2851
Name: count, dtype: int64

--- crm_progress_towards_accreditation ---
crm_progress_towards_accreditation
Yes              53395
Not Discussed    45953
NaN              21035
No                3006
Name: count, dtype: int64

--- crm_delays_in_accreditation ---
crm_delays_in_accreditation
No                                                                                                                                                                                                                   60816
Yes                                                                                                                                                                                                                  40318
NaN                                                                                                                                                                                                                  21035
Not Discussed                                                                                                                                                                                                         1203
Not Discussed (However, I must answer Yes or No, so I'll choose No as there's no clear indication of delays)                                                                                                             2
Not Discussed is not an option here so I will default to No                                                                                                                                                              2
Not Discussed is not applicable here as there is no mention of accreditation delays, however, the answer to whether there are any delays based on the content provided is: No                                            1
Not Discussed is not applicable here, so I will default to: No                                                                                                                                                           1
Not Discussed but potentially yes as the customer is trying to contact Ian and was told he may be in later or the next day                                                                                               1
Not Discussed (However, considering the context is about a policy and a phone number with no answer, it might imply a delay or issue, but strictly speaking, delays in accreditation are not directly mentioned.)        1
Name: count, dtype: int64

--- crm_contractor_suggested_leave ---
crm_contractor_suggested_leave
No               79371
NaN              21035
Not Discussed    14289
Yes               8694
Name: count, dtype: int64

--- crm_contractor_engagement ---
crm_contractor_engagement
Yes                                                                       71129
No                                                                        31188
NaN                                                                       21035
Not Discussed                                                                11
 and they have chosen to drop clients that require the certification."        2
 the price is too high                                                        1
 indicating dissatisfaction with the service or support provided."            1
 indicating dissatisfaction with the cost."                                   1
 which they claim to have requested last year."                               1
"" indicating dissatisfaction with the service."                              1
Name: count, dtype: int64

--- crm_contractor_sentiment ---
crm_contractor_sentiment
Neutral                                     53576
Not Discussed                               31167
NaN                                         21035
Satisfied                                   11405
Dissatisfied                                 6177
Yes                                            20
Initially Dissatisfied, later Neutral           2
No                                              2
 and they are considering cancellation."        1
Initially Dissatisfied, later Satisfied         1
Name: count, dtype: int64

--- crm_contractor_sentiment_score ---
crm_contractor_sentiment_score
50               53554
Not Discussed    31171
NaN              21035
80                7055
20                3006
90                2468
100               1861
40                1477
30                1064
0                  591
Name: count, dtype: int64

--- crm_dts_or_ssip_mentioned ---
crm_dts_or_ssip_mentioned
No               63631
Yes              38697
NaN              21035
20                   7
0                    6
Dissatisfied         4
50                   4
80                   2
Not Discussed        2
30                   1
Name: count, dtype: int64

--- crm_customer_payment_intention ---
crm_customer_payment_intention
Not Discussed    69476
Yes              28236
NaN              21035
No                4638
0                    2
20                   1
30                   1
Name: count, dtype: int64

--- crm_competitors_mentioned ---
crm_competitors_mentioned
No                                           79549
Not Discussed                                26957
NaN                                          11155
Yes                                           5724
Yes (Avetta is mentioned as a competitor)        3
Yes (Avetta mentioned as a competitor)           1
Name: count, dtype: int64

--- crm_membership_level ---
crm_membership_level
In progress       45219
Accredited        35847
Not Discussed     29891
NaN               11155
Members only        854
Standard            162
Not Accredited      104
In Progress          23
Silver               17
Gold                 13
Name: count, dtype: int64

--- crm_platform_issues_raised ---
crm_platform_issues_raised
No               84965
Not Discussed    19946
NaN              11155
Yes               7323
Name: count, dtype: int64

--- crm_agent_chased_contractor ---
crm_agent_chased_contractor
Yes              75030
No               36710
NaN              11155
Not Discussed      494
Name: count, dtype: int64

--- crm_agent_chase_count ---
crm_agent_chase_count
1      25459
2      23726
0      19321
0      17878
NaN    11155
3      10397
1       5764
4       4791
5       3027
7        590
Name: count, dtype: int64

--- crm_accreditation_issues ---
crm_accreditation_issues
Not Discussed    54235
Yes              44787
No               13212
NaN              11155
Name: count, dtype: int64

--- crm_membership_overdue ---
crm_membership_overdue
Not Discussed                                                     54110
Yes                                                               30137
No                                                                27937
NaN                                                               11155
 as a ""Deem to Satisfy"" for their CHAS accreditation                1
 despite being up to date."                                           1
 which they requested to be removed and the invoice reissued."        1
 and the manner in which it was executed."                            1
 preventing them from renewing their membership."                     1
 which is not currently included."                                    1
Name: count, dtype: int64

--- crm_auto_renewal_status ---
crm_auto_renewal_status
0                                                   80050
0                                                   25085
NaN                                                 11155
2                                                    4702
1                                                    2348
Not Discussed                                          20
No                                                     14
Yes                                                     7
 rendering their current accreditation invalid."        1
 potentially up to 8 months."                           1
Name: count, dtype: int64

--- crm_dissatisified_with_renewal_price ---
crm_dissatisified_with_renewal_price
Not Discussed                                                                 70611
No                                                                            33063
NaN                                                                           11155
Yes                                                                            8519
0                                                                                38
2                                                                                 2
No actions or steps were taken by the agent in the provided email content.        1
Name: count, dtype: int64

--- crm_customer_complained ---
crm_customer_complained
No                                                                          104315
NaN                                                                          11475
Yes                                                                           7568
Not Discussed                                                                   16
Not applicable (there is no content to analyze)                                  2
Not applicable (there is no call transcript or email content to analyze)         2
Not applicable (there is no call mentioned in the email content)                 2
Not applicable (there is no call transcript provided)                            2
[Yes/No]                                                                         1
Not applicable (no email content provided)                                       1
Name: count, dtype: int64

--- crm_refund_mentioned ---
crm_refund_mentioned
No                                                                110163
NaN                                                                11475
Yes                                                                 1700
Not Discussed                                                         27
 feeling it implied their evidence was not legitimate                  1
 which provides laundry services for top London hotels."               1
 which would dramatically affect their business."                      1
 and the additional cost for expedited review."                        1
 despite their accreditation and insurances being up to date."         1
 which the agent was not aware of."                                    1
Name: count, dtype: int64

--- crm_negative_customer_experience ---
crm_negative_customer_experience
No                                                       66587
Not Discussed                                            26962
Yes                                                      18360
NaN                                                      11475
 and also expressed concerns about the audit process         1
[Yes/No/Not Discussed]                                       1
 causing them to lose work."                                 1
Not applicable (no email content provided)                   1
Not applicable (there is no email content to analyze)        1
Name: count, dtype: int64

--- crm_dissatisfaction_with_support ---
crm_dissatisfaction_with_support
No                                                                      66336
Not Discussed                                                           34818
NaN                                                                     11475
Yes                                                                     10698
 indicating a negative experience."                                         5
 indicating a potential issue with the accreditation process."              3
 indicating a negative experience with the accreditation process."          2
 indicating a sense of urgency and frustration."                            2
 indicating a negative experience due to personal or health issues."        1
"" which may impact their eligibility for projects."                        1
Name: count, dtype: int64

--- crm_financial_hardship_mentioned ---
crm_financial_hardship_mentioned
Not Discussed                                                                                                                                   72242
No                                                                                                                                              33120
NaN                                                                                                                                             11475
Yes                                                                                                                                              6516
Yes                                                                                                                                                29
 city is required"" message."                                                                                                                       1
 bye""."                                                                                                                                            1
[Yes/No/Not Discussed]                                                                                                                              1
"The Contractor expressed frustration due to the issue with ""24 hour locksmiths"" and the inconvenience with the payment link not working."        1
 safety                                                                                                                                             1
Name: count, dtype: int64

--- year ---
year
2025    81625
2026    41762
2024        2
Name: count, dtype: int64

Handling NULL values for categorical and flag columns

In [8]:
# The data contains columns that have 'Yes', 'No', and 'Not Discussed' 
# We fill missing values with 'Not Discussed' where appropriate.
cat_cols = df_em.select_dtypes(include=['object']).columns

for col in cat_cols:
    if col not in ['Co_Ref', 'Time_to_Renewal']:
        df_em[col] = df_em[col].fillna('Not Discussed')

C:\Users\MadhavGoyal\AppData\Local\Temp\ipykernel_16644\1224569791.py:3: Pandas4Warning: For backward compatibility, 'str' dtypes are included by select_dtypes when 'object' dtype is specified. This behavior is deprecated and will be removed in a future version. Explicitly pass 'str' to `include` to select them, or to `exclude` to remove them and silence this warning.
See https://pandas.pydata.org/docs/user_guide/migration-3-strings.html#string-migration-select-dtypes for details on how to write code that works with pandas 2 and 3.
  cat_cols = df_em.select_dtypes(include=['object']).columns

Cleaning flag columns (Yes/No type) - standardizing free-text comments, stray numbers, and inconsistent entries into proper Yes/No/Not Discussed flags.

In [9]:
flag_cols = [
    'crm_accreditation_completed', 'crm_timely_completion', 'crm_progress_towards_accreditation',
    'crm_delays_in_accreditation', 'crm_contractor_suggested_leave', 'crm_contractor_engagement',
    'crm_dts_or_ssip_mentioned', 'crm_customer_payment_intention', 'crm_competitors_mentioned',
    'crm_platform_issues_raised', 'crm_agent_chased_contractor', 'crm_accreditation_issues',
    'crm_membership_overdue', 'crm_dissatisified_with_renewal_price', 'crm_customer_complained',
    'crm_refund_mentioned', 'crm_negative_customer_experience', 'crm_dissatisfaction_with_support',
    'crm_financial_hardship_mentioned'
]

valid_flags = ['Yes', 'No', 'Not Discussed']

for col in flag_cols:
    if col in df_em.columns:
        df_em[col] = df_em[col].astype(str).str.strip()
        # Map '0' to 'No'
        df_em[col] = df_em[col].replace({'0': 'No'})
        # Anything that is not a valid flag is a free-text comment, map to 'Yes'
        invalid_mask = ~df_em[col].isin(valid_flags)
        df_em.loc[invalid_mask, col] = 'Yes'

Verify flag columns now only contain Yes / No / Not Discussed

In [10]:
for col in flag_cols:
    if col in df_em.columns:
        print(f"{col}: {df_em[col].unique()}")

crm_accreditation_completed: <StringArray>
['Not Discussed', 'No', 'Yes']
Length: 3, dtype: str
crm_timely_completion: <StringArray>
['Not Discussed', 'No', 'Yes']
Length: 3, dtype: str
crm_progress_towards_accreditation: <StringArray>
['Not Discussed', 'Yes', 'No']
Length: 3, dtype: str
crm_delays_in_accreditation: <StringArray>
['Yes', 'No', 'Not Discussed']
Length: 3, dtype: str
crm_contractor_suggested_leave: <StringArray>
['No', 'Not Discussed', 'Yes']
Length: 3, dtype: str
crm_contractor_engagement: <StringArray>
['Yes', 'No', 'Not Discussed']
Length: 3, dtype: str
crm_dts_or_ssip_mentioned: <StringArray>
['No', 'Yes', 'Not Discussed']
Length: 3, dtype: str
crm_customer_payment_intention: <StringArray>
['No', 'Not Discussed', 'Yes']
Length: 3, dtype: str
crm_competitors_mentioned: <StringArray>
['No', 'Not Discussed', 'Yes']
Length: 3, dtype: str
crm_platform_issues_raised: <StringArray>
['No', 'Yes', 'Not Discussed']
Length: 3, dtype: str
crm_agent_chased_contractor: <StringArray>
['Yes', 'No', 'Not Discussed']
Length: 3, dtype: str
crm_accreditation_issues: <StringArray>
['Not Discussed', 'No', 'Yes']
Length: 3, dtype: str
crm_membership_overdue: <StringArray>
['Yes', 'Not Discussed', 'No']
Length: 3, dtype: str
crm_dissatisified_with_renewal_price: <StringArray>
['No', 'Not Discussed', 'Yes']
Length: 3, dtype: str
crm_customer_complained: <StringArray>
['No', 'Yes', 'Not Discussed']
Length: 3, dtype: str
crm_refund_mentioned: <StringArray>
['Yes', 'No', 'Not Discussed']
Length: 3, dtype: str
crm_negative_customer_experience: <StringArray>
['Yes', 'Not Discussed', 'No']
Length: 3, dtype: str
crm_dissatisfaction_with_support: <StringArray>
['No', 'Yes', 'Not Discussed']
Length: 3, dtype: str
crm_financial_hardship_mentioned: <StringArray>
['Yes', 'Not Discussed', 'No']
Length: 3, dtype: str

Cleaning the crm_contractor_sentiment column - it should only have Neutral, Satisfied, Dissatisfied, or Not Discussed

In [11]:
print("Before cleaning:")
print(df_em['crm_contractor_sentiment'].value_counts())

Before cleaning:
crm_contractor_sentiment
Neutral                                                                    53576
Not Discussed                                                              52202
Satisfied                                                                  11405
Dissatisfied                                                                6177
Yes                                                                           20
Initially Dissatisfied, later Neutral                                          2
No                                                                             2
 and they are considering cancellation."                                       1
Initially Dissatisfied, later Satisfied                                        1
 and believes the requests for qualifications and RAMS are ridiculous."        1
 and protecting people."                                                       1
 and no work gained from the membership."                                      1
Name: count, dtype: int64

In [12]:
# 'Yes' and 'No' do not belong in a sentiment column, map them to 'Not Discussed'
valid_sentiments = ['Neutral', 'Satisfied', 'Dissatisfied', 'Not Discussed']
df_em['crm_contractor_sentiment'] = df_em['crm_contractor_sentiment'].apply(
    lambda x: x if x in valid_sentiments else 'Not Discussed'
)

print("After cleaning:")
print(df_em['crm_contractor_sentiment'].value_counts())

After cleaning:
crm_contractor_sentiment
Neutral          53576
Not Discussed    52231
Satisfied        11405
Dissatisfied      6177
Name: count, dtype: int64

Cleaning the crm_contractor_sentiment_score column - converting to numeric, removing text labels like 'Dissatisfied', 'Neutral', 'Yes', etc.

In [13]:
print("Before cleaning:")
print(df_em['crm_contractor_sentiment_score'].value_counts().head(15))

Before cleaning:
crm_contractor_sentiment_score
50               53554
Not Discussed    52206
80                7055
20                3006
90                2468
100               1861
40                1477
30                1064
0                  591
Dissatisfied        14
60                   9
38                   7
37                   4
95                   4
70                   4
Name: count, dtype: int64

In [14]:
# Replace 'Not Discussed' with NaN, then coerce everything to numeric
df_em['crm_contractor_sentiment_score'] = df_em['crm_contractor_sentiment_score'].replace('Not Discussed', np.nan)
df_em['crm_contractor_sentiment_score'] = pd.to_numeric(df_em['crm_contractor_sentiment_score'], errors='coerce')

# Fill remaining NaN with the median of non-null values
median_score = df_em['crm_contractor_sentiment_score'].median()
df_em['crm_contractor_sentiment_score'] = df_em['crm_contractor_sentiment_score'].fillna(median_score)

print(f"Median score used for fill: {median_score}")
print(df_em['crm_contractor_sentiment_score'].describe())

Median score used for fill: 50.0
count    123389.000000
mean         52.010540
std          12.494462
min           0.000000
25%          50.000000
50%          50.000000
75%          50.000000
max         100.000000
Name: crm_contractor_sentiment_score, dtype: float64

Normalizing the crm_membership_level column - consolidating all variants into clean base tiers. Since counts for edge cases are very low (1-8), we merge them into the base tier (Gold, Silver, Bronze, etc.)

In [15]:
print("Before cleaning:")
print(df_em['crm_membership_level'].value_counts())

Before cleaning:
crm_membership_level
In progress                                                       45219
Not Discussed                                                     41046
Accredited                                                        35847
Members only                                                        854
Standard                                                            162
Not Accredited                                                      104
In Progress                                                          23
Silver                                                               17
Gold                                                                 13
Premier                                                              10
Standard membership level                                             9
Membership (Standard)                                                 8
Accredited (Gold level)                                               7
Standard membership                                                   6
Bronze                                                                5
Express                                                               4
Gold level                                                            3
Accredited at Silver level                                            3
Accredited (Silver level)                                             3
Premier Band B                                                        2
Band C1 (5-9 employees)                                               2
Membership (Premier)                                                  2
Premier package                                                       2
Accredited (Bronze level)                                             2
Silver level                                                          2
Member Only                                                           2
Express membership level                                              2
Premier services                                                      1
Group Membership                                                      1
Premier Band C2                                                       1
Base membership                                                       1
Standard Band B                                                       1
Assisted Band C1                                                      1
Membership (PREMIER)                                                  1
Band B                                                                1
Premier Band E                                                        1
Standard membership level (upgraded to Express)                       1
Accredited at the Gold level                                          1
Accredited (SUSPENDED)                                                1
Premier Band D                                                        1
Standard level of membership                                          1
Accredited at Gold level                                              1
Accredited (Silver level, later upgraded to Gold)                     1
Accredited at Bronze level                                            1
Premier package £704 + VAT                                            1
Accredited (Gold)                                                     1
Membership Only                                                       1
Accredited (Gold level OBC)                                           1
Verified at Gold                                                      1
Renewal Complete                                                      1
Standard package                                                      1
Band D (15-29 employees)                                              1
Prem                                                                  1
Accredited (implied by the context, but not explicitly stated)        1
Standard Membership                                                   1
Standard-Safe contractor Membership                                   1
Existing member                                                       1
Name: count, dtype: int64

In [16]:
def normalize_membership(val):
    if pd.isna(val):
        return 'Not Discussed'
    val = val.strip().lower()
    
    # Not useful / not discussed
    if val in ['not discussed', 'yes', 'no', 'renewal complete', 'existing member',
               'accredited (implied by the context, but not explicitly stated)']:
        return 'Not Discussed'
    
    # In Progress
    elif val in ['in progress']:
        return 'In Progress'
    
    # Gold - includes all accredited-at-gold variants
    elif 'gold' in val:
        return 'Gold'
    
    # Silver - includes all accredited-at-silver variants
    elif 'silver' in val:
        return 'Silver'
    
    # Bronze - includes all accredited-at-bronze variants
    elif 'bronze' in val:
        return 'Bronze'
    
    # Accredited (plain, without tier) and suspended
    elif val in ['accredited', 'accredited (suspended)']:
        return 'Accredited'
    
    # Not Accredited
    elif val in ['not accredited']:
        return 'Not Accredited'
    
    # Members Only
    elif val in ['members only', 'member only', 'membership only', 'base membership', 'group membership']:
        return 'Members Only'
    
    # Standard - includes all standard variants
    elif 'standard' in val or val in ['membership (standard)']:
        return 'Standard'
    
    # Premier - includes all premier/prem variants
    elif 'premier' in val or val in ['prem', 'membership (premier)']:
        return 'Premier'
    
    # Express
    elif 'express' in val:
        return 'Express'
    
    # Band/Assisted patterns
    elif 'assisted' in val or 'band' in val:
        return 'Other'
    
    else:
        return 'Other'

df_em['crm_membership_level'] = df_em['crm_membership_level'].apply(normalize_membership)

print("\nAfter cleaning:")
print(df_em['crm_membership_level'].value_counts())

After cleaning:
crm_membership_level
In Progress       45242
Not Discussed     41049
Accredited        35848
Members Only        859
Standard            191
Not Accredited      104
Gold                 29
Silver               25
Premier              23
Bronze                8
Express               6
Other                 5
Name: count, dtype: int64

Cleaning the crm_auto_renewal_status column - converting to numeric with 0 = not set, 1 = active, 2 = other status

In [17]:
print("Before cleaning:")
print(df_em['crm_auto_renewal_status'].value_counts(dropna=False))

Before cleaning:
crm_auto_renewal_status
0                                                                                  80050
0                                                                                  25085
Not Discussed                                                                      11175
2                                                                                   4702
1                                                                                   2348
No                                                                                    14
Yes                                                                                    7
 rendering their current accreditation invalid."                                       1
 potentially up to 8 months."                                                          1
 and over-querying of supplied evidence."                                              1
 and not being familiar with it."                                                      1
 and also had to provide additional information for the accreditation process."        1
 but was helped to correct this by the agent."                                         1
 including evidence of face masks and Respiratory Protective Equipment (RPE)."         1
 and employer's liability."                                                            1
Name: count, dtype: int64

In [18]:
# Map text values and fill NaN
df_em['crm_auto_renewal_status'] = df_em['crm_auto_renewal_status'].replace({
    'Yes': '1', 'No': '0', 'Not Discussed': '0'
})
df_em['crm_auto_renewal_status'] = pd.to_numeric(df_em['crm_auto_renewal_status'], errors='coerce').fillna(0).astype(int)

print("After cleaning:")
print(df_em['crm_auto_renewal_status'].value_counts())

After cleaning:
crm_auto_renewal_status
0    116332
2      4702
1      2355
Name: count, dtype: int64

Cleaning numerical counts (like crm_agent_chase_count)

In [19]:
if 'crm_agent_chase_count' in df_em.columns:
    # Standardize textual representations of counts
    df_em['crm_agent_chase_count'] = df_em['crm_agent_chase_count'].replace({
        'More than 5': '6', 
        'Multiple': '3'
    })
    # Convert to numeric, coerce errors for anything remaining
    df_em['crm_agent_chase_count'] = pd.to_numeric(df_em['crm_agent_chase_count'], errors='coerce').fillna(0).astype(int)

print(df_em['crm_agent_chase_count'].value_counts().head(10))

crm_agent_chase_count
0    48834
1    31223
2    23726
3    10444
4     4791
5     3027
6      591
7      590
8       85
9       38
Name: count, dtype: int64

Final verification - checking remaining null values and dtypes after all cleaning

In [20]:
print("Remaining null values:")
print(df_em.isnull().sum())
print(f"\nTotal rows: {len(df_em)}")
print(f"Total columns: {len(df_em.columns)}")

Remaining null values:
Co_Ref                                  0
Time_to_Renewal                         0
crm_accreditation_completed             0
crm_timely_completion                   0
crm_progress_towards_accreditation      0
crm_delays_in_accreditation             0
crm_contractor_suggested_leave          0
crm_contractor_engagement               0
crm_contractor_sentiment                0
crm_contractor_sentiment_score          0
crm_dts_or_ssip_mentioned               0
crm_customer_payment_intention          0
crm_competitors_mentioned               0
crm_membership_level                    0
crm_platform_issues_raised              0
crm_agent_chased_contractor             0
crm_agent_chase_count                   0
crm_accreditation_issues                0
crm_membership_overdue                  0
crm_auto_renewal_status                 0
crm_dissatisified_with_renewal_price    0
crm_customer_complained                 0
crm_refund_mentioned                    0
crm_negative_customer_experience        0
crm_dissatisfaction_with_support        0
crm_financial_hardship_mentioned        0
year                                    0
dtype: int64

Total rows: 123389
Total columns: 27

In [21]:
df_em.dtypes

Co_Ref                                      str
Time_to_Renewal                             str
crm_accreditation_completed                 str
crm_timely_completion                       str
crm_progress_towards_accreditation          str
crm_delays_in_accreditation                 str
crm_contractor_suggested_leave              str
crm_contractor_engagement                   str
crm_contractor_sentiment                    str
crm_contractor_sentiment_score          float64
crm_dts_or_ssip_mentioned                   str
crm_customer_payment_intention              str
crm_competitors_mentioned                   str
crm_membership_level                        str
crm_platform_issues_raised                  str
crm_agent_chased_contractor                 str
crm_agent_chase_count                     int64
crm_accreditation_issues                    str
crm_membership_overdue                      str
crm_auto_renewal_status                   int64
crm_dissatisified_with_renewal_price        str
crm_customer_complained                     str
crm_refund_mentioned                        str
crm_negative_customer_experience            str
crm_dissatisfaction_with_support            str
crm_financial_hardship_mentioned            str
year                                      int64
dtype: object

Giving type Category to categorical columns

In [22]:
cat_cols = [
    'Time_to_Renewal', 'crm_accreditation_completed', 'crm_timely_completion',
    'crm_progress_towards_accreditation', 'crm_delays_in_accreditation',
    'crm_contractor_suggested_leave', 'crm_contractor_engagement',
    'crm_contractor_sentiment', 'crm_dts_or_ssip_mentioned',
    'crm_customer_payment_intention', 'crm_competitors_mentioned',
    'crm_membership_level', 'crm_platform_issues_raised',
    'crm_agent_chased_contractor', 'crm_accreditation_issues',
    'crm_membership_overdue', 'crm_dissatisified_with_renewal_price',
    'crm_customer_complained', 'crm_refund_mentioned',
    'crm_negative_customer_experience', 'crm_dissatisfaction_with_support',
    'crm_financial_hardship_mentioned'
]

for col in cat_cols:
    df_em[col] = df_em[col].astype('category')

In [23]:
df_em.info()

<class 'pandas.DataFrame'>
RangeIndex: 123389 entries, 0 to 123388
Data columns (total 27 columns):
 #   Column                                Non-Null Count   Dtype
---  ------                                --------------   -----
 0   Co_Ref                                123389 non-null  str
 1   Time_to_Renewal                       123389 non-null  category
 2   crm_accreditation_completed           123389 non-null  category
 3   crm_timely_completion                 123389 non-null  category
 4   crm_progress_towards_accreditation    123389 non-null  category
 5   crm_delays_in_accreditation           123389 non-null  category
 6   crm_contractor_suggested_leave        123389 non-null  category
 7   crm_contractor_engagement             123389 non-null  category
 8   crm_contractor_sentiment              123389 non-null  category
 9   crm_contractor_sentiment_score        123389 non-null  float64
 10  crm_dts_or_ssip_mentioned             123389 non-null  category
 11  crm_customer_payment_intention        123389 non-null  category
 12  crm_competitors_mentioned             123389 non-null  category
 13  crm_membership_level                  123389 non-null  category
 14  crm_platform_issues_raised            123389 non-null  category
 15  crm_agent_chased_contractor           123389 non-null  category
 16  crm_agent_chase_count                 123389 non-null  int64
 17  crm_accreditation_issues              123389 non-null  category
 18  crm_membership_overdue                123389 non-null  category
 19  crm_auto_renewal_status               123389 non-null  int64
 20  crm_dissatisified_with_renewal_price  123389 non-null  category
 21  crm_customer_complained               123389 non-null  category
 22  crm_refund_mentioned                  123389 non-null  category
 23  crm_negative_customer_experience      123389 non-null  category
 24  crm_dissatisfaction_with_support      123389 non-null  category
 25  crm_financial_hardship_mentioned      123389 non-null  category
 26  year                                  123389 non-null  int64
dtypes: category(22), float64(1), int64(3), str(1)
memory usage: 7.3 MB

In [24]:
df_em.head()

,Co_Ref,Time_to_Renewal,crm_accreditation_completed,crm_timely_completion,crm_progress_towards_accreditation,crm_delays_in_accreditation,crm_contractor_suggested_leave,crm_contractor_engagement,crm_contractor_sentiment,crm_contractor_sentiment_score,...,crm_accreditation_issues,crm_membership_overdue,crm_auto_renewal_status,crm_dissatisified_with_renewal_price,crm_customer_complained,crm_refund_mentioned,crm_negative_customer_experience,crm_dissatisfaction_with_support,crm_financial_hardship_mentioned,year
0,KG5766,pre_renewal,Not Discussed,Not Discussed,Not Discussed,Yes,No,Yes,Neutral,50.0,...,Not Discussed,Yes,0,No,No,Yes,Yes,No,Yes,2025
1,EJ1532,14_out,Not Discussed,Not Discussed,Not Discussed,No,Not Discussed,No,Not Discussed,50.0,...,Not Discussed,Not Discussed,0,Not Discussed,No,Yes,Yes,No,Not Discussed,2025
2,AA4063,prior_year,Not Discussed,Not Discussed,Not Discussed,No,No,Yes,Neutral,50.0,...,Not Discussed,No,0,No,No,Yes,Yes,Yes,Not Discussed,2025
3,JY9888,prior_year,No,No,Not Discussed,Yes,No,Yes,Satisfied,80.0,...,Not Discussed,Yes,0,Not Discussed,No,Yes,Yes,No,Not Discussed,2025
4,WO6689,pre_renewal,Not Discussed,Not Discussed,Not Discussed,No,No,Yes,Satisfied,80.0,...,No,No,0,No,No,Yes,Yes,No,Not Discussed,2026

Saving the cleaned dataset

In [25]:
import os

# Ensure the clean data directory exists
clean_data_path = project_root / "data" / "processed"
os.makedirs(clean_data_path, exist_ok=True)

# Write out to clean folder
out_file = clean_data_path / "cleaned_emails.csv"
df_em.to_csv(out_file, index=False)
print(f"Cleaned dataset saved successfully to {out_file}")

Cleaned dataset saved successfully to c:\Users\MadhavGoyal\Desktop\DS Project'\Churn-Prediction\data\processed\cleaned_emails.csv