In [37]:
import pandas as pd
import numpy as np

In [38]:
%pip install openpyxl

Requirement already satisfied: openpyxl in c:\Users\ShefaliChopra\AppData\Local\Programs\Python\Python314\Lib\site-packages (3.1.5)
Requirement already satisfied: et-xmlfile in c:\Users\ShefaliChopra\AppData\Local\Programs\Python\Python314\Lib\site-packages (from openpyxl) (2.0.0)
Note: you may need to restart the kernel to use updated packages.

WARNING: Ignoring invalid distribution ~ip (c:\Users\ShefaliChopra\AppData\Local\Programs\Python\Python314\Lib\site-packages)
WARNING: Ignoring invalid distribution ~ip (c:\Users\ShefaliChopra\AppData\Local\Programs\Python\Python314\Lib\site-packages)
WARNING: Ignoring invalid distribution ~ip (c:\Users\ShefaliChopra\AppData\Local\Programs\Python\Python314\Lib\site-packages)

In [39]:


from pathlib import Path


project_root = Path.cwd().parent.parent
data_path = project_root / "data" / "raw" / "renewal_calls.xlsx"


df_rc = pd.read_excel(data_path, sheet_name=0, header=0)

df_rc.head(10)

,Call_ID,Co_Ref,Call_Date,Churn_Category,Complaint_Category,Customer_Reaction_Category,Agent_Renewal_Pitch_Category,Customer_Renewal_Response_Category,Agent_Response_Category,Membership_Renewal_Decision,...,Call_Year,Desire_To_Cancel,Call_Direction,Unnamed: 38,Unnamed: 39,Unnamed: 40,Unnamed: 41,Unnamed: 42,Unnamed: 43,Unnamed: 44
0,595125621875,UB0899,2025-01-29,NaN,NaN,Not Mentioned,Discussion / Introduction / Inquiry,Discount and Offer,Discount and Offer,No,...,2025,Not Discussed,Outbound,NaN,NaN,NaN,NaN,NaN,NaN,NaN
1,596924831511,HN5141,2025-02-26,NaN,NaN,NaN,Price and Cost,Agreement,Customer Communication,No,...,2025,Not Discussed,OUT_BOUND,NaN,NaN,NaN,NaN,NaN,NaN,NaN
2,594704125359,BP5009,2025-01-24,NaN,NaN,NaN,Expiration / Due,Agreement,Accreditation and Certification,No,...,2025,Not Discussed,Outbound,NaN,NaN,NaN,NaN,NaN,NaN,NaN
3,651566331360,XP8119,2025-06-09,NaN,NaN,NaN,Auto / Automatic,Agreement,Accreditation and Certification,No,...,2025,Not Discussed,OUT_BOUND,NaN,NaN,NaN,NaN,NaN,NaN,NaN
4,537381000452,ZL7978,2024-08-20,NaN,NaN,NaN,NaN,NaN,NaN,No,...,2024,Not Discussed,Outbound,NaN,NaN,NaN,NaN,NaN,NaN,NaN
5,596041347563,ZD2578,2025-02-13,NaN,NaN,NaN,NaN,NaN,NaN,No,...,2025,Not Discussed,IN_BOUND,NaN,NaN,NaN,NaN,NaN,NaN,NaN
6,596926478285,XQ7113,2025-02-28,NaN,NaN,NaN,Cancellation / Termination / Non-Renewal / Clo...,Discount and Offer,Cancellation / Termination / Closure,No,...,2025,Desired to Cancel,OUT_BOUND,NaN,NaN,NaN,NaN,NaN,NaN,NaN
7,513208265991,KS3954,2024-08-19,NaN,NaN,NaN,Expiration / Due,Payments and Billings / Invoice,Confirmation / Acceptance / Agreement,No,...,2024,Not Discussed,Outbound,NaN,NaN,NaN,NaN,NaN,NaN,NaN
8,595126227393,MQ5878,2025-01-30,NaN,NaN,NaN,Payment and Billings / Invoice,Payments and Billings / Invoice,Customer Communication,No,...,2025,Not Discussed,Outbound,NaN,NaN,NaN,NaN,NaN,NaN,NaN
9,593697406883,NaN,2025-01-08,NaN,NaN,NaN,NaN,NaN,NaN,No,...,2025,Not Discussed,Inbound,NaN,NaN,NaN,NaN,NaN,NaN,NaN

In [40]:
# axis=1 means target columns
# how='all' means only drop if every value in the column is missing
df_rc = df_rc.dropna(axis=1, how='all')

# Verify the change
print(f"Columns remaining: {df_rc.columns.tolist()}")

Columns remaining: ['Call_ID', 'Co_Ref', 'Call_Date', 'Churn_Category', 'Complaint_Category', 'Customer_Reaction_Category', 'Agent_Renewal_Pitch_Category', 'Customer_Renewal_Response_Category', 'Agent_Response_Category', 'Membership_Renewal_Decision', 'Serious_Complaint', 'Other_Complaint', 'Discussion_on_Price_Increase', 'Renewal_Impact_Due_to_Price_Increase', 'Discount_or_Waiver_Requested', 'Call_Reschedule_Request', 'Agent_Flagged_Membership_Status_Alert', 'Agent_Renewal_Initiation', 'Explicit_Competitor_Mention', 'Implied_Competitor_Mention', 'Explicit_Switching_Intent', 'Implied_Switching_Intent', 'Mentioned_Competitors', 'Price_Switching_Mentioned', 'Competitor_Benefits_Mentioned', 'Topic_Introduced_By', 'Renewal_Fee_Mentioned', 'Percentage_Price_Increase_Mentioned', 'Monetary_Price_Increase_Mentioned', 'Customer_Asked_For_Justification', 'Discount_Offered', 'Justification_Category', 'Reason_For_Renewal_Category', 'Agent_Response_To_Cancel_Category', 'Analysed_Call', 'Call_Year', 'Desire_To_Cancel', 'Call_Direction', 'Unnamed: 38', 'Unnamed: 39', 'Unnamed: 40', 'Unnamed: 41', 'Unnamed: 42', 'Unnamed: 43', 'Unnamed: 44']

In [41]:
# This keeps only columns that don't start with the word 'Unnamed'
df_rc = df_rc.loc[:, ~df_rc.columns.str.contains('^Unnamed')]

df_rc.head()

,Call_ID,Co_Ref,Call_Date,Churn_Category,Complaint_Category,Customer_Reaction_Category,Agent_Renewal_Pitch_Category,Customer_Renewal_Response_Category,Agent_Response_Category,Membership_Renewal_Decision,...,Monetary_Price_Increase_Mentioned,Customer_Asked_For_Justification,Discount_Offered,Justification_Category,Reason_For_Renewal_Category,Agent_Response_To_Cancel_Category,Analysed_Call,Call_Year,Desire_To_Cancel,Call_Direction
0,595125621875,UB0899,2025-01-29,NaN,NaN,Not Mentioned,Discussion / Introduction / Inquiry,Discount and Offer,Discount and Offer,No,...,No,No,No,NaN,NaN,NaN,1,2025,Not Discussed,Outbound
1,596924831511,HN5141,2025-02-26,NaN,NaN,NaN,Price and Cost,Agreement,Customer Communication,No,...,No,No,No,NaN,NaN,NaN,1,2025,Not Discussed,OUT_BOUND
2,594704125359,BP5009,2025-01-24,NaN,NaN,NaN,Expiration / Due,Agreement,Accreditation and Certification,No,...,No,No,No,NaN,NaN,NaN,1,2025,Not Discussed,Outbound
3,651566331360,XP8119,2025-06-09,NaN,NaN,NaN,Auto / Automatic,Agreement,Accreditation and Certification,No,...,No,No,No,NaN,NaN,NaN,1,2025,Not Discussed,OUT_BOUND
4,537381000452,ZL7978,2024-08-20,NaN,NaN,NaN,NaN,NaN,NaN,No,...,No,No,No,NaN,NaN,NaN,1,2024,Not Discussed,Outbound

In [42]:


# Check null counts per column
print(df_rc.isnull().sum())

Call_ID                                       0
Co_Ref                                     7385
Call_Date                                     0
Churn_Category                           178626
Complaint_Category                       167521
Customer_Reaction_Category               163444
Agent_Renewal_Pitch_Category             132796
Customer_Renewal_Response_Category       132222
Agent_Response_Category                  132554
Membership_Renewal_Decision               99960
Serious_Complaint                        102201
Other_Complaint                          102202
Discussion_on_Price_Increase              98500
Renewal_Impact_Due_to_Price_Increase      98529
Discount_or_Waiver_Requested              98529
Call_Reschedule_Request                   97956
Agent_Flagged_Membership_Status_Alert     97956
Agent_Renewal_Initiation                  97956
Explicit_Competitor_Mention               97830
Implied_Competitor_Mention                97830
Explicit_Switching_Intent                 97830
Implied_Switching_Intent                  97830
Mentioned_Competitors                     97828
Price_Switching_Mentioned                 97872
Competitor_Benefits_Mentioned             99956
Topic_Introduced_By                       97813
Renewal_Fee_Mentioned                     97813
Percentage_Price_Increase_Mentioned       97813
Monetary_Price_Increase_Mentioned         97813
Customer_Asked_For_Justification          97813
Discount_Offered                          97814
Justification_Category                   173452
Reason_For_Renewal_Category              170396
Agent_Response_To_Cancel_Category        181600
Analysed_Call                             97790
Call_Year                                     0
Desire_To_Cancel                          97817
Call_Direction                                4
dtype: int64

Handling NULL values for categorical columns

In [43]:
# List of categorical columns with high null counts
cat_cols = [
    'Churn_Category', 'Complaint_Category', 'Customer_Reaction_Category', 
    'Agent_Renewal_Pitch_Category', 'Customer_Renewal_Response_Category',
    'Mentioned_Competitors', 'Justification_Category', 'Reason_For_Renewal_Category'
]

# Fill with 'Not Mentioned' or 'None'
df_rc[cat_cols] = df_rc[cat_cols].fillna('Not Mentioned')

In [44]:
df_rc.head(10)

,Call_ID,Co_Ref,Call_Date,Churn_Category,Complaint_Category,Customer_Reaction_Category,Agent_Renewal_Pitch_Category,Customer_Renewal_Response_Category,Agent_Response_Category,Membership_Renewal_Decision,...,Monetary_Price_Increase_Mentioned,Customer_Asked_For_Justification,Discount_Offered,Justification_Category,Reason_For_Renewal_Category,Agent_Response_To_Cancel_Category,Analysed_Call,Call_Year,Desire_To_Cancel,Call_Direction
0,595125621875,UB0899,2025-01-29,Not Mentioned,Not Mentioned,Not Mentioned,Discussion / Introduction / Inquiry,Discount and Offer,Discount and Offer,No,...,No,No,No,Not Mentioned,Not Mentioned,NaN,1,2025,Not Discussed,Outbound
1,596924831511,HN5141,2025-02-26,Not Mentioned,Not Mentioned,Not Mentioned,Price and Cost,Agreement,Customer Communication,No,...,No,No,No,Not Mentioned,Not Mentioned,NaN,1,2025,Not Discussed,OUT_BOUND
2,594704125359,BP5009,2025-01-24,Not Mentioned,Not Mentioned,Not Mentioned,Expiration / Due,Agreement,Accreditation and Certification,No,...,No,No,No,Not Mentioned,Not Mentioned,NaN,1,2025,Not Discussed,Outbound
3,651566331360,XP8119,2025-06-09,Not Mentioned,Not Mentioned,Not Mentioned,Auto / Automatic,Agreement,Accreditation and Certification,No,...,No,No,No,Not Mentioned,Not Mentioned,NaN,1,2025,Not Discussed,OUT_BOUND
4,537381000452,ZL7978,2024-08-20,Not Mentioned,Not Mentioned,Not Mentioned,Not Mentioned,Not Mentioned,NaN,No,...,No,No,No,Not Mentioned,Not Mentioned,NaN,1,2024,Not Discussed,Outbound
5,596041347563,ZD2578,2025-02-13,Not Mentioned,Not Mentioned,Not Mentioned,Not Mentioned,Not Mentioned,NaN,No,...,No,No,No,Not Mentioned,Not Mentioned,NaN,1,2025,Not Discussed,IN_BOUND
6,596926478285,XQ7113,2025-02-28,Not Mentioned,Not Mentioned,Not Mentioned,Cancellation / Termination / Non-Renewal / Clo...,Discount and Offer,Cancellation / Termination / Closure,No,...,No,No,No,Not Mentioned,Not Mentioned,NaN,1,2025,Desired to Cancel,OUT_BOUND
7,513208265991,KS3954,2024-08-19,Not Mentioned,Not Mentioned,Not Mentioned,Expiration / Due,Payments and Billings / Invoice,Confirmation / Acceptance / Agreement,No,...,No,No,No,Not Mentioned,Not Mentioned,NaN,1,2024,Not Discussed,Outbound
8,595126227393,MQ5878,2025-01-30,Not Mentioned,Not Mentioned,Not Mentioned,Payment and Billings / Invoice,Payments and Billings / Invoice,Customer Communication,No,...,No,No,No,Not Mentioned,Not Mentioned,NaN,1,2025,Not Discussed,Outbound
9,593697406883,NaN,2025-01-08,Not Mentioned,Not Mentioned,Not Mentioned,Not Mentioned,Not Mentioned,NaN,No,...,No,No,No,Not Mentioned,Not Mentioned,NaN,1,2025,Not Discussed,Inbound

In [45]:
# List of indicator columns
flag_cols = [
    'Serious_Complaint', 'Other_Complaint', 'Discount_or_Waiver_Requested',
    'Call_Reschedule_Request', 'Explicit_Competitor_Mention', 'Explicit_Switching_Intent'
]

# Option A: Fill with 0 (Assuming Null means No)
df_rc[flag_cols] = df_rc[flag_cols].fillna(0)

# Option B: If they are strings like 'Yes'/NaN, map them:
df_rc['Serious_Complaint'] = df_rc['Serious_Complaint'].map({'Yes': 1}).fillna(0)

In [46]:
# Create a clean 'discount_reason' column by extracting text inside brackets
# This looks for anything between ( and )
df_rc['discount_reason'] = df_rc['Discount_or_Waiver_Requested'].str.extract(r'\((.*?)\)')

# Fill the new column's nulls
df_rc['discount_reason'] = df_rc['discount_reason'].fillna('No Request')

In [47]:
# If there is any value (even with numbers), mark as 1. If Null, mark as 0.
df_rc['asked_for_discount'] = df_rc['Discount_or_Waiver_Requested'].notnull().astype(int)

In [48]:
# Remove digits and special characters from the reason
df_rc['discount_reason'] = df_rc['discount_reason'].str.replace(r'\d+', '', regex=True).str.strip()

In [65]:
# Check null counts per column
print(df_rc.isnull().sum())

Call_ID                                       0
Co_Ref                                     7385
Call_Date                                     0
Churn_Category                                0
Complaint_Category                            0
Customer_Reaction_Category                    0
Agent_Renewal_Pitch_Category                  0
Customer_Renewal_Response_Category            0
Agent_Response_Category                       0
Membership_Renewal_Decision               99960
Serious_Complaint                             0
Other_Complaint                               0
Discussion_on_Price_Increase              98500
Renewal_Impact_Due_to_Price_Increase      98529
Discount_or_Waiver_Requested                  0
Call_Reschedule_Request                       0
Agent_Flagged_Membership_Status_Alert     97956
Agent_Renewal_Initiation                  97956
Explicit_Competitor_Mention                   0
Implied_Competitor_Mention                97830
Explicit_Switching_Intent                     0
Implied_Switching_Intent                  97830
Mentioned_Competitors                         0
Price_Switching_Mentioned                 97872
Competitor_Benefits_Mentioned             99956
Topic_Introduced_By                       97813
Renewal_Fee_Mentioned                     97813
Percentage_Price_Increase_Mentioned       97813
Monetary_Price_Increase_Mentioned         97813
Customer_Asked_For_Justification          97813
Discount_Offered                          97814
Justification_Category                        0
Reason_For_Renewal_Category                   0
Agent_Response_To_Cancel_Category        181600
Analysed_Call                                 0
Call_Year                                     0
Desire_To_Cancel                          97817
Call_Direction                                0
discount_reason                               0
asked_for_discount                            0
discount_applied_flag                         0
Analysed_Call_Status                          0
intent_category                               0
intent_reason                                 0
has_desired_to_cancel                         0
cancel_reason                                 0
dtype: int64

In [52]:
# 1. Identify rows where the 'Call_Direction' is actually a long sentence
mask = df_rc['Call_Direction'].str.len() > 20

# 2. Fill in the gaps based on that sentence
# We can assume if they are 'renewing', the decision is 'Yes'
df_rc.loc[mask, 'Membership_Renewal_Decision'] = 'Renewed'
df_rc.loc[mask, 'Customer_Reaction_Category'] = 'Positive'

# 3. Fix the 'Call_Direction' column so it only contains 'Outbound' or 'Inbound'
# Since an agent was assisted, we'll label these as Outbound 
df_rc.loc[mask, 'Call_Direction'] = 'Outbound'

# 4. Fill the remaining empty ones 
df_rc['Call_Direction'] = df_rc['Call_Direction'].fillna('Unknown')

# Convert to lowercase, remove underscores, and strip extra spaces
df_rc['Call_Direction'] = df_rc['Call_Direction'].str.lower().str.replace('_', '').str.strip()

# Verify the result
print(df_rc['Call_Direction'].unique())

<StringArray>
['outbound', 'inbound', 'unknown']
Length: 3, dtype: str

Analyze_Call column cleaning

In [53]:
# Create a flag if the analyzed call mentions a discount
df_rc['discount_applied_flag'] = df_rc['Analysed_Call'].str.contains('discount', case=False, na=False).astype(int)

In [54]:
import numpy as np

def categorize_analysis(val):
    val = str(val).strip()
    if val == 'nan' or val == 'NULL' or val == '':
        return 'Not Analysed'
    elif val.isdigit() and len(val) > 5:
        return 'ID/Numeric Record'
    elif 'Agent' in val or 'Customer' in val:
        return 'Detailed Summary'
    elif val in ['1', '3', 'Discounts/ incentives']:
        return 'Standard Category'
    else:
        return 'Other'

df_rc['Analysed_Call_Status'] = df_rc['Analysed_Call'].apply(categorize_analysis)

In [55]:
# Fill the original column nulls so the code doesn't break later
df_rc['Analysed_Call'] = df_rc['Analysed_Call'].fillna('No Analysis Available')

Desire to cancel column cleaning

In [64]:
import pandas as pd

# 1. Create the Boolean Flag
# We look for 'Desired to Cancel'. 
# Note: 'Undecided' will be False here. If you want Undecided to be True, 
# use: .str.contains('Desired to Cancel|Undecided', ...)
df_rc['has_desired_to_cancel'] = df_rc['Desire_To_Cancel'].str.contains('Desired to Cancel', case=False, na=False)

# 2. Extract the Reason (text inside brackets)
df_rc['cancel_reason'] = df_rc['Desire_To_Cancel'].str.extract(r'\((.*?)\)')

# 3. Clean up the Reason column
# Fill empty brackets/Nulls with 'No Reason Given'
df_rc['cancel_reason'] = df_rc['cancel_reason'].fillna('No Reason Given')

# If the original column had 'NAME' or 'Undecided' without brackets, 
# we label that as the reason so we don't lose that info.
df_rc.loc[df_rc['Desire_To_Cancel'].str.contains('NAME', na=False), 'cancel_reason'] = 'Personal Mention'
df_rc.loc[df_rc['Desire_To_Cancel'].str.contains('Undecided', na=False), 'cancel_reason'] = 'Undecided'

# 4. Verify
print(df_rc[['Desire_To_Cancel', 'has_desired_to_cancel', 'cancel_reason']].value_counts().head(10))

Desire_To_Cancel                                                                has_desired_to_cancel  cancel_reason
Renewed                                                                         False                  No Reason Given    40361
Not Discussed                                                                   False                  No Reason Given    36153
Desired to Cancel                                                               True                   No Reason Given    10733
Renew                                                                           False                  No Reason Given      726
Not Applicable                                                                  False                  No Reason Given       52
Desired to Cancel (initially), but considering renewal after the agent's offer  True                   initially             28
Desired to Renew                                                                False                  No Reason Given       27
Renewal not discussed                                                           False                  No Reason Given       25
[Renewed / Desired to Cancel]                                                   True                   No Reason Given       18
Desired to Cancel (initially), but considering renewal after discussion         True                   initially             17
Name: count, dtype: int64

In [59]:
print(df_rc['cancel_reason'].value_counts().head(10))

cancel_reason
No Reason Given                                       185973
initially                                                172
implied, but not explicitly stated                        11
but considering renewal                                    7
Not Discussed                                              6
implied, not explicitly stated                             5
temporarily, due to financial constraints                  4
initially undecided, but leaning towards canceling         4
Undecided                                                  3
initially, but open to renewal after discussion            3
Name: count, dtype: int64

In [61]:
# Standardize NULLs and 'Not Mentioned' into a single category
df_rc['Agent_Response_Category'] = df_rc['Agent_Response_Category'].fillna('Not Mentioned')

# If 'Not Mentioned' is already a string, this ensures they are identical
df_rc['Agent_Response_Category'] = df_rc['Agent_Response_Category'].replace(['NULL', 'nan', 'none'], 'Not Mentioned')

# Verify the result
print(df_rc['Agent_Response_Category'].value_counts())

Agent_Response_Category
Not Mentioned                            133285
Payment                                   10308
Customer Communication                     9635
Confirmation / Acceptance / Agreement      6935
Customer Service / Support                 4330
Customer Retention                         3740
Cancellation / Termination / Closure       3643
Accreditation and Certification            3181
Account information                        2840
Discount and Offer                         2467
Auto / Automatic                           2249
Price and Cost                             1503
Audit                                       992
Assessment                                  396
Technical                                   367
Benefits and Package                        227
Refund                                      204
Complaints                                  104
Insurance                                    71
Others                                       51
Name: count, dtype: int64

In [62]:
# 1. Fill actual NaN values first
df_rc['Agent_Response_Category'] = df_rc['Agent_Response_Category'].fillna('Not Mentioned')

# 2. Standardize string versions of 'Null' or 'NaN'
# We use a list of common "junk" strings found in Excel exports
junk_labels = ['null', 'nan', 'none', 'n/a', 'not mentioned', '']

df_rc['Agent_Response_Category'] = df_rc['Agent_Response_Category'].apply(
    lambda x: 'Not Mentioned' if str(x).strip().lower() in junk_labels else x
)

# 3. Quick check of your top 10 categories
print(df_rc['Agent_Response_Category'].value_counts().head(10))

Agent_Response_Category
Not Mentioned                            133285
Payment                                   10308
Customer Communication                     9635
Confirmation / Acceptance / Agreement      6935
Customer Service / Support                 4330
Customer Retention                         3740
Cancellation / Termination / Closure       3643
Accreditation and Certification            3181
Account information                        2840
Discount and Offer                         2467
Name: count, dtype: int64

Membership_Renewal_Decision column cleaning

In [66]:


# 1. Fill actual NaNs with 'Pending/Unknown'
df_rc['Membership_Renewal_Decision'] = df_rc['Membership_Renewal_Decision'].fillna('Pending/Unknown')

# 2. Define a mapping dictionary to standardize the strings
# This handles the 'Yes/No' cases as 'Pending' to keep the model accurate
decision_map = {
    'Yes': 'Renewed',
    'No': 'Cancelled',
    'Yes/No': 'Pending/Unknown',
    'NULL': 'Pending/Unknown',
    'nan': 'Pending/Unknown'
}

# 3. Apply the mapping
# We use .get() so that any values already cleaned (like 'Renewed') stay as they are
df_rc['Membership_Renewal_Decision'] = df_rc['Membership_Renewal_Decision'].apply(
    lambda x: decision_map.get(x, x)
)

# 4. Verify the distribution
print(df_rc['Membership_Renewal_Decision'].value_counts())

Membership_Renewal_Decision
Pending/Unknown    99974
Cancelled          77543
Renewed             9011
Name: count, dtype: int64