In [1]:
import pandas as pd
import numpy as np

Using the Path library to read the file

In [2]:


from pathlib import Path


project_root = Path.cwd().parent.parent
data_path = project_root / "data" / "raw" / "renewal_calls.csv"


df_rc = pd.read_csv(data_path, header=0)

df_rc.head(10)

C:\Users\madha\AppData\Local\Temp\ipykernel_6468\2278243943.py:8: DtypeWarning: Columns (4,5,6,7,8,9,10,11,12,13,14,15,16,17,18,19,21,22,23,24,25,26,27,28,29,30,31,32,33,34,35,36,37) have mixed types. Specify dtype option on import or set low_memory=False.
  df_rc = pd.read_csv(data_path, header=0)

,Call_ID,Call_Direction,Co_Ref,Call_Date,Churn_Category,Complaint_Category,Customer_Reaction_Category,Agent_Renewal_Pitch_Category,Customer_Renewal_Response_Category,Agent_Response_Category,...,Customer_Response,Desire_To_Cancel,Discount_Offered,Justification_Category,Reason_For_Renewal_Category,Agent_Response_To_Cancel_Category,Argument_That_Convinced_Customer_to_Stay_Category,Analysed_Call,Call_Number,Call_Year
0,5.950000e+11,Outbound,UB0899,29-01-2025,NaN,NaN,Not Mentioned,Discussion / Introduction / Inquiry,Discount and Offer,Discount and Offer,...,Not Discussed,Not Discussed,No,NaN,NaN,NaN,NaN,1.0,3,2025
1,5.970000e+11,OUT_BOUND,HN5141,26-02-2025,NaN,NaN,NaN,Price and Cost,Agreement,Customer Communication,...,Not Discussed,Not Discussed,No,NaN,NaN,NaN,NaN,1.0,2,2025
2,5.950000e+11,Outbound,BP5009,24-01-2025,NaN,NaN,NaN,Expiration / Due,Agreement,Accreditation and Certification,...,Not Discussed,Not Discussed,No,NaN,NaN,NaN,NaN,1.0,1,2025
3,6.520000e+11,OUT_BOUND,XP8119,09-06-2025,NaN,NaN,NaN,Auto / Automatic,Agreement,Accreditation and Certification,...,Not Discussed,Not Discussed,No,NaN,NaN,NaN,NaN,1.0,1,2025
4,5.370000e+11,Outbound,ZL7978,20-08-2024,NaN,NaN,NaN,NaN,NaN,NaN,...,Not Discussed,Not Discussed,No,NaN,NaN,NaN,NaN,1.0,28,2024
5,5.960000e+11,IN_BOUND,ZD2578,13-02-2025,NaN,NaN,NaN,NaN,NaN,NaN,...,Not Discussed,Not Discussed,No,NaN,NaN,NaN,NaN,1.0,1,2025
6,5.970000e+11,OUT_BOUND,XQ7113,28-02-2025,NaN,NaN,NaN,Cancellation / Termination / Non-Renewal / Clo...,Discount and Offer,Cancellation / Termination / Closure,...,Neutral,Desired to Cancel,No,NaN,NaN,NaN,NaN,1.0,7,2025
7,5.130000e+11,Outbound,KS3954,19-08-2024,NaN,NaN,NaN,Expiration / Due,Payments and Billings / Invoice,Confirmation / Acceptance / Agreement,...,Not Discussed,Not Discussed,No,NaN,NaN,NaN,NaN,1.0,1,2024
8,5.950000e+11,Outbound,MQ5878,30-01-2025,NaN,NaN,NaN,Payment and Billings / Invoice,Payments and Billings / Invoice,Customer Communication,...,Not Discussed,Not Discussed,No,NaN,NaN,NaN,NaN,1.0,3,2025
9,5.940000e+11,Inbound,NaN,08-01-2025,NaN,NaN,NaN,NaN,NaN,NaN,...,Not Discussed,Not Discussed,No,NaN,NaN,NaN,NaN,1.0,3494,2025

This dataset contains call transcript metadata from renewal conversations, capturing the interactions between agents and customers during the critical subscription renewal window. 
It tracks customer sentiment and intent (such as desire to cancel or complaints), agent intervention strategies (like discount offers or specific renewal pitches), and competitive intelligence regarding rival pricing or benefits. 
The primary goal of this data is to serve as a predictor for post-renewal churn, allowing you to identify which "saved" customers are still at high risk of leaving in the future.

In [3]:
df_rc.dtypes

Call_ID                                              float64
Call_Direction                                        object
Co_Ref                                                object
Call_Date                                             object
Churn_Category                                        object
Complaint_Category                                    object
Customer_Reaction_Category                            object
Agent_Renewal_Pitch_Category                          object
Customer_Renewal_Response_Category                    object
Agent_Response_Category                               object
Membership_Renewal_Decision                           object
Serious_Complaint                                     object
Other_Complaint                                       object
Discussion_on_Price_Increase                          object
Renewal_Impact_Due_to_Price_Increase                  object
Discount_or_Waiver_Requested                          object
Call_Reschedule_Request                               object
Agent_Flagged_Membership_Status_Alert                 object
Agent_Renewal_Initiation                              object
Explicit_Competitor_Mention                           object
Unnamed: 20                                          float64
Explicit_Switching_Intent                             object
Mentioned_Competitors                                 object
Price_Switching_Mentioned                             object
Competitor_Value_Comparison                           object
Competitor_Benefits_Mentioned                         object
Topic_Introduced_By                                   object
Percentage_Price_Increase_Mentioned                   object
Monetary_Price_Increase_Mentioned                     object
Price_Range_Mentioned                                 object
Customer_Asked_For_Justification                      object
Customer_Response                                     object
Desire_To_Cancel                                      object
Discount_Offered                                      object
Justification_Category                                object
Reason_For_Renewal_Category                           object
Agent_Response_To_Cancel_Category                     object
Argument_That_Convinced_Customer_to_Stay_Category     object
Analysed_Call                                        float64
Call_Number                                            int64
Call_Year                                              int64
dtype: object

Drop columns that are completely null.

In [4]:
# axis=1 means target columns
# how='all' means only drop if every value in the column is missing
df_rc = df_rc.dropna(axis=1, how='all')

# Verify the change
print(f"Columns remaining: {df_rc.columns.tolist()}")

Columns remaining: ['Call_ID', 'Call_Direction', 'Co_Ref', 'Call_Date', 'Churn_Category', 'Complaint_Category', 'Customer_Reaction_Category', 'Agent_Renewal_Pitch_Category', 'Customer_Renewal_Response_Category', 'Agent_Response_Category', 'Membership_Renewal_Decision', 'Serious_Complaint', 'Other_Complaint', 'Discussion_on_Price_Increase', 'Renewal_Impact_Due_to_Price_Increase', 'Discount_or_Waiver_Requested', 'Call_Reschedule_Request', 'Agent_Flagged_Membership_Status_Alert', 'Agent_Renewal_Initiation', 'Explicit_Competitor_Mention', 'Explicit_Switching_Intent', 'Mentioned_Competitors', 'Price_Switching_Mentioned', 'Competitor_Value_Comparison', 'Competitor_Benefits_Mentioned', 'Topic_Introduced_By', 'Percentage_Price_Increase_Mentioned', 'Monetary_Price_Increase_Mentioned', 'Price_Range_Mentioned', 'Customer_Asked_For_Justification', 'Customer_Response', 'Desire_To_Cancel', 'Discount_Offered', 'Justification_Category', 'Reason_For_Renewal_Category', 'Agent_Response_To_Cancel_Category', 'Argument_That_Convinced_Customer_to_Stay_Category', 'Analysed_Call', 'Call_Number', 'Call_Year']

Removing unnamed columns

In [5]:
# This keeps only columns that don't start with the word 'Unnamed'
df_rc = df_rc.loc[:, ~df_rc.columns.str.contains('^Unnamed')]

df_rc.head()

,Call_ID,Call_Direction,Co_Ref,Call_Date,Churn_Category,Complaint_Category,Customer_Reaction_Category,Agent_Renewal_Pitch_Category,Customer_Renewal_Response_Category,Agent_Response_Category,...,Customer_Response,Desire_To_Cancel,Discount_Offered,Justification_Category,Reason_For_Renewal_Category,Agent_Response_To_Cancel_Category,Argument_That_Convinced_Customer_to_Stay_Category,Analysed_Call,Call_Number,Call_Year
0,5.950000e+11,Outbound,UB0899,29-01-2025,NaN,NaN,Not Mentioned,Discussion / Introduction / Inquiry,Discount and Offer,Discount and Offer,...,Not Discussed,Not Discussed,No,NaN,NaN,NaN,NaN,1.0,3,2025
1,5.970000e+11,OUT_BOUND,HN5141,26-02-2025,NaN,NaN,NaN,Price and Cost,Agreement,Customer Communication,...,Not Discussed,Not Discussed,No,NaN,NaN,NaN,NaN,1.0,2,2025
2,5.950000e+11,Outbound,BP5009,24-01-2025,NaN,NaN,NaN,Expiration / Due,Agreement,Accreditation and Certification,...,Not Discussed,Not Discussed,No,NaN,NaN,NaN,NaN,1.0,1,2025
3,6.520000e+11,OUT_BOUND,XP8119,09-06-2025,NaN,NaN,NaN,Auto / Automatic,Agreement,Accreditation and Certification,...,Not Discussed,Not Discussed,No,NaN,NaN,NaN,NaN,1.0,1,2025
4,5.370000e+11,Outbound,ZL7978,20-08-2024,NaN,NaN,NaN,NaN,NaN,NaN,...,Not Discussed,Not Discussed,No,NaN,NaN,NaN,NaN,1.0,28,2024

check for null values for every column

In [6]:
# Check null counts per column
print(df_rc.isnull().sum())

Call_ID                                                   0
Call_Direction                                            0
Co_Ref                                                 7385
Call_Date                                                 0
Churn_Category                                       178632
Complaint_Category                                   167526
Customer_Reaction_Category                           163449
Agent_Renewal_Pitch_Category                         132796
Customer_Renewal_Response_Category                   132222
Agent_Response_Category                              132554
Membership_Renewal_Decision                           99960
Serious_Complaint                                    102201
Other_Complaint                                      102202
Discussion_on_Price_Increase                          98500
Renewal_Impact_Due_to_Price_Increase                  98529
Discount_or_Waiver_Requested                          98529
Call_Reschedule_Request                               97956
Agent_Flagged_Membership_Status_Alert                 97956
Agent_Renewal_Initiation                              97956
Explicit_Competitor_Mention                           97830
Explicit_Switching_Intent                             97830
Mentioned_Competitors                                 97828
Price_Switching_Mentioned                             97872
Competitor_Value_Comparison                           97869
Competitor_Benefits_Mentioned                         99956
Topic_Introduced_By                                   97813
Percentage_Price_Increase_Mentioned                   97813
Monetary_Price_Increase_Mentioned                     97813
Price_Range_Mentioned                                 97813
Customer_Asked_For_Justification                      97813
Customer_Response                                     97813
Desire_To_Cancel                                      97816
Discount_Offered                                      97813
Justification_Category                               173454
Reason_For_Renewal_Category                          170399
Agent_Response_To_Cancel_Category                    181607
Argument_That_Convinced_Customer_to_Stay_Category    184716
Analysed_Call                                         97790
Call_Number                                               0
Call_Year                                                 0
dtype: int64

Handling NULL values for categorical columns

In [7]:
# List of categorical columns with high null counts
cat_cols = [
    'Churn_Category', 'Complaint_Category', 'Customer_Reaction_Category', 
    'Agent_Renewal_Pitch_Category', 'Customer_Renewal_Response_Category',
    'Mentioned_Competitors', 'Justification_Category', 'Reason_For_Renewal_Category'
]

# Fill with 'Not Mentioned' or 'None'
df_rc[cat_cols] = df_rc[cat_cols].fillna('Not Mentioned')

In [8]:
df_rc.head(10)

,Call_ID,Call_Direction,Co_Ref,Call_Date,Churn_Category,Complaint_Category,Customer_Reaction_Category,Agent_Renewal_Pitch_Category,Customer_Renewal_Response_Category,Agent_Response_Category,...,Customer_Response,Desire_To_Cancel,Discount_Offered,Justification_Category,Reason_For_Renewal_Category,Agent_Response_To_Cancel_Category,Argument_That_Convinced_Customer_to_Stay_Category,Analysed_Call,Call_Number,Call_Year
0,5.950000e+11,Outbound,UB0899,29-01-2025,Not Mentioned,Not Mentioned,Not Mentioned,Discussion / Introduction / Inquiry,Discount and Offer,Discount and Offer,...,Not Discussed,Not Discussed,No,Not Mentioned,Not Mentioned,NaN,NaN,1.0,3,2025
1,5.970000e+11,OUT_BOUND,HN5141,26-02-2025,Not Mentioned,Not Mentioned,Not Mentioned,Price and Cost,Agreement,Customer Communication,...,Not Discussed,Not Discussed,No,Not Mentioned,Not Mentioned,NaN,NaN,1.0,2,2025
2,5.950000e+11,Outbound,BP5009,24-01-2025,Not Mentioned,Not Mentioned,Not Mentioned,Expiration / Due,Agreement,Accreditation and Certification,...,Not Discussed,Not Discussed,No,Not Mentioned,Not Mentioned,NaN,NaN,1.0,1,2025
3,6.520000e+11,OUT_BOUND,XP8119,09-06-2025,Not Mentioned,Not Mentioned,Not Mentioned,Auto / Automatic,Agreement,Accreditation and Certification,...,Not Discussed,Not Discussed,No,Not Mentioned,Not Mentioned,NaN,NaN,1.0,1,2025
4,5.370000e+11,Outbound,ZL7978,20-08-2024,Not Mentioned,Not Mentioned,Not Mentioned,Not Mentioned,Not Mentioned,NaN,...,Not Discussed,Not Discussed,No,Not Mentioned,Not Mentioned,NaN,NaN,1.0,28,2024
5,5.960000e+11,IN_BOUND,ZD2578,13-02-2025,Not Mentioned,Not Mentioned,Not Mentioned,Not Mentioned,Not Mentioned,NaN,...,Not Discussed,Not Discussed,No,Not Mentioned,Not Mentioned,NaN,NaN,1.0,1,2025
6,5.970000e+11,OUT_BOUND,XQ7113,28-02-2025,Not Mentioned,Not Mentioned,Not Mentioned,Cancellation / Termination / Non-Renewal / Clo...,Discount and Offer,Cancellation / Termination / Closure,...,Neutral,Desired to Cancel,No,Not Mentioned,Not Mentioned,NaN,NaN,1.0,7,2025
7,5.130000e+11,Outbound,KS3954,19-08-2024,Not Mentioned,Not Mentioned,Not Mentioned,Expiration / Due,Payments and Billings / Invoice,Confirmation / Acceptance / Agreement,...,Not Discussed,Not Discussed,No,Not Mentioned,Not Mentioned,NaN,NaN,1.0,1,2024
8,5.950000e+11,Outbound,MQ5878,30-01-2025,Not Mentioned,Not Mentioned,Not Mentioned,Payment and Billings / Invoice,Payments and Billings / Invoice,Customer Communication,...,Not Discussed,Not Discussed,No,Not Mentioned,Not Mentioned,NaN,NaN,1.0,3,2025
9,5.940000e+11,Inbound,NaN,08-01-2025,Not Mentioned,Not Mentioned,Not Mentioned,Not Mentioned,Not Mentioned,NaN,...,Not Discussed,Not Discussed,No,Not Mentioned,Not Mentioned,NaN,NaN,1.0,3494,2025

Filling categorical column's null values

In [9]:

flag_cols = [
    'Serious_Complaint', 'Other_Complaint', 'Discount_or_Waiver_Requested',
    'Call_Reschedule_Request', 'Explicit_Competitor_Mention', 'Explicit_Switching_Intent'
]

df_rc[flag_cols] = df_rc[flag_cols].fillna(0)

df_rc['Serious_Complaint'] = df_rc['Serious_Complaint'].map({'Yes': 1}).fillna(0)

cleaning discount_reason column derived from Discount_or_Waiver_Requested column to get the reason separately

In [10]:
# Create a clean discount_reason column by extracting text inside brackets
df_rc['discount_reason'] = df_rc['Discount_or_Waiver_Requested'].str.extract(r'\((.*?)\)')

# Fill the new column's nulls
df_rc['discount_reason'] = df_rc['discount_reason'].fillna('No Request')

creating asked_for_discount to understand if the customer asked for a discount or not

In [11]:
# If there is any value (even with numbers), mark as 1. If Null, mark as 0.
df_rc['asked_for_discount'] = df_rc['Discount_or_Waiver_Requested'].notnull().astype(int)

stripping the reason

In [12]:
# Remove digits and special characters from the reason
df_rc['discount_reason'] = df_rc['discount_reason'].str.replace(r'\d+', '', regex=True).str.strip()

checking the null values

In [13]:
# Check null counts per column
print(df_rc.isnull().sum())

Call_ID                                                   0
Call_Direction                                            0
Co_Ref                                                 7385
Call_Date                                                 0
Churn_Category                                            0
Complaint_Category                                        0
Customer_Reaction_Category                                0
Agent_Renewal_Pitch_Category                              0
Customer_Renewal_Response_Category                        0
Agent_Response_Category                              132554
Membership_Renewal_Decision                           99960
Serious_Complaint                                         0
Other_Complaint                                           0
Discussion_on_Price_Increase                          98500
Renewal_Impact_Due_to_Price_Increase                  98529
Discount_or_Waiver_Requested                              0
Call_Reschedule_Request                                   0
Agent_Flagged_Membership_Status_Alert                 97956
Agent_Renewal_Initiation                              97956
Explicit_Competitor_Mention                               0
Explicit_Switching_Intent                                 0
Mentioned_Competitors                                     0
Price_Switching_Mentioned                             97872
Competitor_Value_Comparison                           97869
Competitor_Benefits_Mentioned                         99956
Topic_Introduced_By                                   97813
Percentage_Price_Increase_Mentioned                   97813
Monetary_Price_Increase_Mentioned                     97813
Price_Range_Mentioned                                 97813
Customer_Asked_For_Justification                      97813
Customer_Response                                     97813
Desire_To_Cancel                                      97816
Discount_Offered                                      97813
Justification_Category                                    0
Reason_For_Renewal_Category                               0
Agent_Response_To_Cancel_Category                    181607
Argument_That_Convinced_Customer_to_Stay_Category    184716
Analysed_Call                                         97790
Call_Number                                               0
Call_Year                                                 0
discount_reason                                           0
asked_for_discount                                        0
dtype: int64

Cleaning the Call_Direction column and masking it based on conversation, integrating with Membership_Renewal_Decision and Customer_Reaction_Category.

In [14]:
# Identify rows where the Call_Direction is actually a long sentence
mask = df_rc['Call_Direction'].str.len() > 20

# Fill in the gaps based on that sentence
# assuming if they are 'renewing', the decision is 'Yes'
df_rc.loc[mask, 'Membership_Renewal_Decision'] = 'Renewed'
df_rc.loc[mask, 'Customer_Reaction_Category'] = 'Positive'

# Fix the Call_Direction column so it only contains 'Outbound' or 'Inbound'
# Since an agent was assisted, label these as Outbound 
df_rc.loc[mask, 'Call_Direction'] = 'Outbound'

# Fill the remaining empty ones 
df_rc['Call_Direction'] = df_rc['Call_Direction'].fillna('Unknown')

# Convert to lowercase, remove underscores, and strip extra spaces
df_rc['Call_Direction'] = df_rc['Call_Direction'].str.lower().str.replace('_', '').str.strip()

print(df_rc['Call_Direction'].unique())

['outbound' 'inbound']

Analyze_Call column cleaning

In [15]:
import numpy as np

def categorize_analysis(val):
    val = str(val).strip()
    if val == 'nan' or val == 'NULL' or val == '':
        return 'Not Analysed'
    elif val.isdigit() and len(val) > 5:
        return 'ID/Numeric Record'
    elif 'Agent' in val or 'Customer' in val:
        return 'Detailed Summary'
    elif val in ['1', '3', 'Discounts/ incentives']:
        return 'Standard Category'
    else:
        return 'Other'

df_rc['Analysed_Call_Status'] = df_rc['Analysed_Call'].apply(categorize_analysis)

In [16]:
df_rc['Analysed_Call'] = df_rc['Analysed_Call'].fillna('No Analysis Available')

Desire to cancel column cleaning

In [17]:

# look for Desired to Cancel
df_rc['has_desired_to_cancel'] = df_rc['Desire_To_Cancel'].str.contains('Desired to Cancel', case=False, na=False)

# Extract the Reason 
df_rc['cancel_reason'] = df_rc['Desire_To_Cancel'].str.extract(r'\((.*?)\)')

# Clean up the Reason column
# Fill empty brackets/Nulls with 'No Reason Given'
df_rc['cancel_reason'] = df_rc['cancel_reason'].fillna('No Reason Given')

# If the original column had 'NAME' or 'Undecided' without brackets, 
# we label that as the reason so we don't lose that info.
df_rc.loc[df_rc['Desire_To_Cancel'].str.contains('NAME', na=False), 'cancel_reason'] = 'Personal Mention'
df_rc.loc[df_rc['Desire_To_Cancel'].str.contains('Undecided', na=False), 'cancel_reason'] = 'Undecided'

print(df_rc[['Desire_To_Cancel', 'has_desired_to_cancel', 'cancel_reason']].value_counts().head(10))

Desire_To_Cancel                                                                has_desired_to_cancel  cancel_reason
Renewed                                                                         False                  No Reason Given    40367
Not Discussed                                                                   False                  No Reason Given    36151
Desired to Cancel                                                               True                   No Reason Given    10738
Renew                                                                           False                  No Reason Given      726
Not Applicable                                                                  False                  No Reason Given       51
Desired to Cancel (initially), but considering renewal after the agent's offer  True                   initially             28
Desired to Renew                                                                False                  No Reason Given       27
Renewal not discussed                                                           False                  No Reason Given       25
[Renewed / Desired to Cancel]                                                   True                   No Reason Given       18
Desired to Cancel (initially), but considering renewal after discussion         True                   initially             17
Name: count, dtype: int64

In [18]:
print(df_rc['cancel_reason'].value_counts().head(10))

cancel_reason
No Reason Given                                       185978
initially                                                172
implied, but not explicitly stated                        11
but considering renewal                                    7
Not Discussed                                              6
implied, not explicitly stated                             5
initially undecided, but leaning towards canceling         4
temporarily, due to financial constraints                  4
initially, but open to renewal after discussion            3
Undecided                                                  3
Name: count, dtype: int64

Cleaning the Agent_Response_Category of nulls

In [19]:
# Standardize NULLs and 'Not Mentioned' into a single category
df_rc['Agent_Response_Category'] = df_rc['Agent_Response_Category'].fillna('Not Mentioned')

# If 'Not Mentioned' is already a string, this ensures they are identical
df_rc['Agent_Response_Category'] = df_rc['Agent_Response_Category'].replace(['NULL', 'nan', 'none'], 'Not Mentioned')

print(df_rc['Agent_Response_Category'].value_counts())

Agent_Response_Category
Not Mentioned                            133285
Payment                                   10308
Customer Communication                     9638
Confirmation / Acceptance / Agreement      6935
Customer Service / Support                 4330
Customer Retention                         3740
Cancellation / Termination / Closure       3643
Accreditation and Certification            3182
Account information                        2840
Discount and Offer                         2468
Auto / Automatic                           2250
Price and Cost                             1503
Audit                                       992
Assessment                                  396
Technical                                   367
Benefits and Package                        227
Refund                                      204
Complaints                                  104
Insurance                                    71
Others                                       51
Name: count, dtype: int64

In [20]:

df_rc['Agent_Response_Category'] = df_rc['Agent_Response_Category'].fillna('Not Mentioned')
junk_labels = ['null', 'nan', 'none', 'n/a', 'not mentioned', '']

df_rc['Agent_Response_Category'] = df_rc['Agent_Response_Category'].apply(
    lambda x: 'Not Mentioned' if str(x).strip().lower() in junk_labels else x
)

print(df_rc['Agent_Response_Category'].value_counts().head(10))

Agent_Response_Category
Not Mentioned                            133285
Payment                                   10308
Customer Communication                     9638
Confirmation / Acceptance / Agreement      6935
Customer Service / Support                 4330
Customer Retention                         3740
Cancellation / Termination / Closure       3643
Accreditation and Certification            3182
Account information                        2840
Discount and Offer                         2468
Name: count, dtype: int64

Membership_Renewal_Decision column cleaning

In [21]:


# Fill actual NaNs with 'Pending/Unknown'
df_rc['Membership_Renewal_Decision'] = df_rc['Membership_Renewal_Decision'].fillna('Pending/Unknown')

# Define a mapping dictionary to standardize the strings
# This handles the 'Yes/No' cases as 'Pending' to keep the model accurate
decision_map = {
    'Yes': 'Renewed',
    'No': 'Cancelled',
    'Yes/No': 'Pending/Unknown',
    'NULL': 'Pending/Unknown',
    'nan': 'Pending/Unknown'
}

df_rc['Membership_Renewal_Decision'] = df_rc['Membership_Renewal_Decision'].apply(
    lambda x: decision_map.get(x, x)
)

print(df_rc['Membership_Renewal_Decision'].value_counts())

Membership_Renewal_Decision
Pending/Unknown    99974
Cancelled          77550
Renewed             9010
Name: count, dtype: int64

Checking nulls

In [22]:
print(df_rc.isnull().sum())

Call_ID                                                   0
Call_Direction                                            0
Co_Ref                                                 7385
Call_Date                                                 0
Churn_Category                                            0
Complaint_Category                                        0
Customer_Reaction_Category                                0
Agent_Renewal_Pitch_Category                              0
Customer_Renewal_Response_Category                        0
Agent_Response_Category                                   0
Membership_Renewal_Decision                               0
Serious_Complaint                                         0
Other_Complaint                                           0
Discussion_on_Price_Increase                          98500
Renewal_Impact_Due_to_Price_Increase                  98529
Discount_or_Waiver_Requested                              0
Call_Reschedule_Request                                   0
Agent_Flagged_Membership_Status_Alert                 97956
Agent_Renewal_Initiation                              97956
Explicit_Competitor_Mention                               0
Explicit_Switching_Intent                                 0
Mentioned_Competitors                                     0
Price_Switching_Mentioned                             97872
Competitor_Value_Comparison                           97869
Competitor_Benefits_Mentioned                         99956
Topic_Introduced_By                                   97813
Percentage_Price_Increase_Mentioned                   97813
Monetary_Price_Increase_Mentioned                     97813
Price_Range_Mentioned                                 97813
Customer_Asked_For_Justification                      97813
Customer_Response                                     97813
Desire_To_Cancel                                      97816
Discount_Offered                                      97813
Justification_Category                                    0
Reason_For_Renewal_Category                               0
Agent_Response_To_Cancel_Category                    181607
Argument_That_Convinced_Customer_to_Stay_Category    184716
Analysed_Call                                             0
Call_Number                                               0
Call_Year                                                 0
discount_reason                                           0
asked_for_discount                                        0
Analysed_Call_Status                                      0
has_desired_to_cancel                                     0
cancel_reason                                             0
dtype: int64

In [23]:
df_rc.head(20)

,Call_ID,Call_Direction,Co_Ref,Call_Date,Churn_Category,Complaint_Category,Customer_Reaction_Category,Agent_Renewal_Pitch_Category,Customer_Renewal_Response_Category,Agent_Response_Category,...,Agent_Response_To_Cancel_Category,Argument_That_Convinced_Customer_to_Stay_Category,Analysed_Call,Call_Number,Call_Year,discount_reason,asked_for_discount,Analysed_Call_Status,has_desired_to_cancel,cancel_reason
0,5.950000e+11,outbound,UB0899,29-01-2025,Not Mentioned,Not Mentioned,Not Mentioned,Discussion / Introduction / Inquiry,Discount and Offer,Discount and Offer,...,NaN,NaN,1.0,3,2025,No Request,1,Other,False,No Reason Given
1,5.970000e+11,outbound,HN5141,26-02-2025,Not Mentioned,Not Mentioned,Not Mentioned,Price and Cost,Agreement,Customer Communication,...,NaN,NaN,1.0,2,2025,No Request,1,Other,False,No Reason Given
2,5.950000e+11,outbound,BP5009,24-01-2025,Not Mentioned,Not Mentioned,Not Mentioned,Expiration / Due,Agreement,Accreditation and Certification,...,NaN,NaN,1.0,1,2025,No Request,1,Other,False,No Reason Given
3,6.520000e+11,outbound,XP8119,09-06-2025,Not Mentioned,Not Mentioned,Not Mentioned,Auto / Automatic,Agreement,Accreditation and Certification,...,NaN,NaN,1.0,1,2025,No Request,1,Other,False,No Reason Given
4,5.370000e+11,outbound,ZL7978,20-08-2024,Not Mentioned,Not Mentioned,Not Mentioned,Not Mentioned,Not Mentioned,Not Mentioned,...,NaN,NaN,1.0,28,2024,No Request,1,Other,False,No Reason Given
5,5.960000e+11,inbound,ZD2578,13-02-2025,Not Mentioned,Not Mentioned,Not Mentioned,Not Mentioned,Not Mentioned,Not Mentioned,...,NaN,NaN,1.0,1,2025,No Request,1,Other,False,No Reason Given
6,5.970000e+11,outbound,XQ7113,28-02-2025,Not Mentioned,Not Mentioned,Not Mentioned,Cancellation / Termination / Non-Renewal / Clo...,Discount and Offer,Cancellation / Termination / Closure,...,NaN,NaN,1.0,7,2025,No Request,1,Other,True,No Reason Given
7,5.130000e+11,outbound,KS3954,19-08-2024,Not Mentioned,Not Mentioned,Not Mentioned,Expiration / Due,Payments and Billings / Invoice,Confirmation / Acceptance / Agreement,...,NaN,NaN,1.0,1,2024,No Request,1,Other,False,No Reason Given
8,5.950000e+11,outbound,MQ5878,30-01-2025,Not Mentioned,Not Mentioned,Not Mentioned,Payment and Billings / Invoice,Payments and Billings / Invoice,Customer Communication,...,NaN,NaN,1.0,3,2025,No Request,1,Other,False,No Reason Given
9,5.940000e+11,inbound,NaN,08-01-2025,Not Mentioned,Not Mentioned,Not Mentioned,Not Mentioned,Not Mentioned,Not Mentioned,...,NaN,NaN,1.0,3494,2025,No Request,1,Other,False,No Reason Given
10,5.070000e+11,outbound,EC6498,03-05-2024,Not Mentioned,Not Mentioned,Not Mentioned,Not Mentioned,Not Mentioned,Not Mentioned,...,NaN,NaN,1.0,2,2024,No Request,1,Other,False,No Reason Given
11,6.250000e+11,outbound,GK7848,23-04-2025,Not Mentioned,Not Mentioned,Not Mentioned,Payment and Billings / Invoice,Agreement,Accreditation and Certification,...,NaN,NaN,1.0,2,2025,No Request,1,Other,False,No Reason Given
12,5.950000e+11,outbound,JD0641,27-01-2025,Not Mentioned,Not Mentioned,Not Mentioned,Not Mentioned,Not Mentioned,Not Mentioned,...,NaN,NaN,1.0,1,2025,No Request,1,Other,False,No Reason Given
13,6.510000e+11,inbound,OV8721,05-06-2025,Not Mentioned,Not Mentioned,Not Mentioned,Accreditation and Certification,Assessment,Audit,...,NaN,NaN,1.0,2,2025,No Request,1,Other,False,No Reason Given
14,5.120000e+11,outbound,SE7937,23-07-2024,Not Mentioned,Not Mentioned,Not Mentioned,Not Mentioned,Not Mentioned,Not Mentioned,...,NaN,NaN,1.0,3,2024,No Request,1,Other,False,No Reason Given
15,6.510000e+11,inbound,CU6905,27-05-2025,Not Mentioned,Not Mentioned,Not Mentioned,Not Mentioned,Not Mentioned,Not Mentioned,...,NaN,NaN,1.0,5,2025,No Request,1,Other,False,No Reason Given
16,6.250000e+11,outbound,KK8083,02-05-2025,Not Mentioned,Not Mentioned,Not Mentioned,Auto / Automatic,Agreement,Account information,...,NaN,NaN,1.0,2,2025,No Request,1,Other,False,No Reason Given
17,6.230000e+11,inbound,OM9757,24-03-2025,Not Mentioned,Not Mentioned,Not Mentioned,Payment and Billings / Invoice,Auto / Automatic,Confirmation / Acceptance / Agreement,...,NaN,NaN,1.0,3,2025,No Request,1,Other,False,No Reason Given
18,5.110000e+11,outbound,NP5270,09-07-2024,Not Mentioned,Not Mentioned,Not Mentioned,Not Mentioned,Not Mentioned,Not Mentioned,...,NaN,NaN,1.0,8,2024,No Request,1,Other,False,No Reason Given
19,5.960000e+11,outbound,PK6935,10-02-2025,Not Mentioned,Not Mentioned,Not Mentioned,Auto / Automatic,Agreement,Confirmation / Acceptance / Agreement,...,NaN,NaN,1.0,1,2025,No Request,1,Other,False,No Reason Given

Co_Ref had many empty values which would make it difficult to join with billing data later so removing null values.

In [24]:
# Drop rows where Co_Ref is missing
df_rc = df_rc.dropna(subset=['Co_Ref'])

Handling other catgeorical columns

In [25]:
# Filling behavioral flags with 0
behavior_flags = [
    'Discussion_on_Price_Increase', 'Renewal_Impact_Due_to_Price_Increase',
    'Agent_Flagged_Membership_Status_Alert', 'Agent_Renewal_Initiation',
    'Price_Switching_Mentioned', 'Competitor_Value_Comparison',
    'Competitor_Benefits_Mentioned', 'Percentage_Price_Increase_Mentioned',
    'Monetary_Price_Increase_Mentioned', 'Price_Range_Mentioned',
    'Customer_Asked_For_Justification', 'Discount_Offered'
]
df_rc[behavior_flags] = df_rc[behavior_flags].fillna(0)

# Filling the new high-null categorical columns
new_cats = [
    'Customer_Response', 'Agent_Response_To_Cancel_Category',
    'Argument_That_Convinced_Customer_to_Stay_Category', 'Topic_Introduced_By'
]
df_rc[new_cats] = df_rc[new_cats].fillna('Not Mentioned')

Converting the call date to datetime and call_id was in scientific number format changing to number

In [26]:
# Convert Call_Date to proper datetime
df_rc['Call_Date'] = pd.to_datetime(df_rc['Call_Date'], dayfirst=True)

# Fix Call_ID formatting so it's a readable string, not scientific notation
df_rc['Call_ID'] = df_rc['Call_ID'].astype('int64')


print(f"Final Null Count: {df_rc.isnull().sum().sum()}")

Final Null Count: 94237

In [27]:
df_rc.dtypes

Call_ID                                                       int64
Call_Direction                                               object
Co_Ref                                                       object
Call_Date                                            datetime64[ns]
Churn_Category                                               object
Complaint_Category                                           object
Customer_Reaction_Category                                   object
Agent_Renewal_Pitch_Category                                 object
Customer_Renewal_Response_Category                           object
Agent_Response_Category                                      object
Membership_Renewal_Decision                                  object
Serious_Complaint                                           float64
Other_Complaint                                              object
Discussion_on_Price_Increase                                 object
Renewal_Impact_Due_to_Price_Increase                         object
Discount_or_Waiver_Requested                                 object
Call_Reschedule_Request                                      object
Agent_Flagged_Membership_Status_Alert                        object
Agent_Renewal_Initiation                                     object
Explicit_Competitor_Mention                                  object
Explicit_Switching_Intent                                    object
Mentioned_Competitors                                        object
Price_Switching_Mentioned                                    object
Competitor_Value_Comparison                                  object
Competitor_Benefits_Mentioned                                object
Topic_Introduced_By                                          object
Percentage_Price_Increase_Mentioned                          object
Monetary_Price_Increase_Mentioned                            object
Price_Range_Mentioned                                        object
Customer_Asked_For_Justification                             object
Customer_Response                                            object
Desire_To_Cancel                                             object
Discount_Offered                                             object
Justification_Category                                       object
Reason_For_Renewal_Category                                  object
Agent_Response_To_Cancel_Category                            object
Argument_That_Convinced_Customer_to_Stay_Category            object
Analysed_Call                                                object
Call_Number                                                   int64
Call_Year                                                     int64
discount_reason                                              object
asked_for_discount                                            int64
Analysed_Call_Status                                         object
has_desired_to_cancel                                          bool
cancel_reason                                                object
dtype: object

In [28]:
print(df_rc.isnull().sum())

Call_ID                                                  0
Call_Direction                                           0
Co_Ref                                                   0
Call_Date                                                0
Churn_Category                                           0
Complaint_Category                                       0
Customer_Reaction_Category                               0
Agent_Renewal_Pitch_Category                             0
Customer_Renewal_Response_Category                       0
Agent_Response_Category                                  0
Membership_Renewal_Decision                              0
Serious_Complaint                                        0
Other_Complaint                                          0
Discussion_on_Price_Increase                             0
Renewal_Impact_Due_to_Price_Increase                     0
Discount_or_Waiver_Requested                             0
Call_Reschedule_Request                                  0
Agent_Flagged_Membership_Status_Alert                    0
Agent_Renewal_Initiation                                 0
Explicit_Competitor_Mention                              0
Explicit_Switching_Intent                                0
Mentioned_Competitors                                    0
Price_Switching_Mentioned                                0
Competitor_Value_Comparison                              0
Competitor_Benefits_Mentioned                            0
Topic_Introduced_By                                      0
Percentage_Price_Increase_Mentioned                      0
Monetary_Price_Increase_Mentioned                        0
Price_Range_Mentioned                                    0
Customer_Asked_For_Justification                         0
Customer_Response                                        0
Desire_To_Cancel                                     94237
Discount_Offered                                         0
Justification_Category                                   0
Reason_For_Renewal_Category                              0
Agent_Response_To_Cancel_Category                        0
Argument_That_Convinced_Customer_to_Stay_Category        0
Analysed_Call                                            0
Call_Number                                              0
Call_Year                                                0
discount_reason                                          0
asked_for_discount                                       0
Analysed_Call_Status                                     0
has_desired_to_cancel                                    0
cancel_reason                                            0
dtype: int64

Dropping the unnecessary column Desire_To_Cancel

In [29]:
df_rc.drop(columns=['Desire_To_Cancel'], inplace=True)

In [30]:
df_rc.head(10)

,Call_ID,Call_Direction,Co_Ref,Call_Date,Churn_Category,Complaint_Category,Customer_Reaction_Category,Agent_Renewal_Pitch_Category,Customer_Renewal_Response_Category,Agent_Response_Category,...,Agent_Response_To_Cancel_Category,Argument_That_Convinced_Customer_to_Stay_Category,Analysed_Call,Call_Number,Call_Year,discount_reason,asked_for_discount,Analysed_Call_Status,has_desired_to_cancel,cancel_reason
0,595000000000,outbound,UB0899,2025-01-29,Not Mentioned,Not Mentioned,Not Mentioned,Discussion / Introduction / Inquiry,Discount and Offer,Discount and Offer,...,Not Mentioned,Not Mentioned,1.0,3,2025,No Request,1,Other,False,No Reason Given
1,597000000000,outbound,HN5141,2025-02-26,Not Mentioned,Not Mentioned,Not Mentioned,Price and Cost,Agreement,Customer Communication,...,Not Mentioned,Not Mentioned,1.0,2,2025,No Request,1,Other,False,No Reason Given
2,595000000000,outbound,BP5009,2025-01-24,Not Mentioned,Not Mentioned,Not Mentioned,Expiration / Due,Agreement,Accreditation and Certification,...,Not Mentioned,Not Mentioned,1.0,1,2025,No Request,1,Other,False,No Reason Given
3,652000000000,outbound,XP8119,2025-06-09,Not Mentioned,Not Mentioned,Not Mentioned,Auto / Automatic,Agreement,Accreditation and Certification,...,Not Mentioned,Not Mentioned,1.0,1,2025,No Request,1,Other,False,No Reason Given
4,537000000000,outbound,ZL7978,2024-08-20,Not Mentioned,Not Mentioned,Not Mentioned,Not Mentioned,Not Mentioned,Not Mentioned,...,Not Mentioned,Not Mentioned,1.0,28,2024,No Request,1,Other,False,No Reason Given
5,596000000000,inbound,ZD2578,2025-02-13,Not Mentioned,Not Mentioned,Not Mentioned,Not Mentioned,Not Mentioned,Not Mentioned,...,Not Mentioned,Not Mentioned,1.0,1,2025,No Request,1,Other,False,No Reason Given
6,597000000000,outbound,XQ7113,2025-02-28,Not Mentioned,Not Mentioned,Not Mentioned,Cancellation / Termination / Non-Renewal / Clo...,Discount and Offer,Cancellation / Termination / Closure,...,Not Mentioned,Not Mentioned,1.0,7,2025,No Request,1,Other,True,No Reason Given
7,513000000000,outbound,KS3954,2024-08-19,Not Mentioned,Not Mentioned,Not Mentioned,Expiration / Due,Payments and Billings / Invoice,Confirmation / Acceptance / Agreement,...,Not Mentioned,Not Mentioned,1.0,1,2024,No Request,1,Other,False,No Reason Given
8,595000000000,outbound,MQ5878,2025-01-30,Not Mentioned,Not Mentioned,Not Mentioned,Payment and Billings / Invoice,Payments and Billings / Invoice,Customer Communication,...,Not Mentioned,Not Mentioned,1.0,3,2025,No Request,1,Other,False,No Reason Given
10,507000000000,outbound,EC6498,2024-05-03,Not Mentioned,Not Mentioned,Not Mentioned,Not Mentioned,Not Mentioned,Not Mentioned,...,Not Mentioned,Not Mentioned,1.0,2,2024,No Request,1,Other,False,No Reason Given

Clubbing the fragmented data, each id has many columns in the data, fixing for better understanding and joining later

In [31]:

# change text like "[Yes]" or "XXXX" into numbers/clean strings 
# so the 'max' logic works correctly

def clean_to_numeric(val):
    val = str(val).strip().lower()
    if val in ['yes', '1', '1.0', '[yes]', 'yes/no']:
        return 1
    return 0

# List of columns that indicate a "Yes/No" or "Presence" of something
flag_cols = [
    'asked_for_discount', 'has_desired_to_cancel', 'Serious_Complaint', 
    'Explicit_Competitor_Mention', 'Explicit_Switching_Intent', 
    'Discount_Offered', 'Discussion_on_Price_Increase'
]

for col in flag_cols:
    if col in df_rc.columns:
        df_rc[col] = df_rc[col].apply(clean_to_numeric)


# Do this BEFORE grouping so we know how many rows were originally there
df_rc['Call_Length_Score'] = df_rc.groupby(['Co_Ref', 'Call_Date'])['Call_ID'].transform('count')

# Logic: Use 'max' for flags (so we don't miss a 'Yes') 
# and 'last' for everything else (to get the final outcome of the call).

# Start with 'last' for every column
agg_dict = {col: 'last' for col in df_rc.columns if col not in ['Co_Ref', 'Call_Date']}

# Update specific columns to use 'max'
for col in flag_cols:
    if col in agg_dict:
        agg_dict[col] = 'max'

# Apply the grouping
df_rc = df_rc.groupby(['Co_Ref', 'Call_Date']).agg(agg_dict).reset_index()


print(f"Cleaning Complete.")
print(f"Total Unique Calls: {len(df_rc)}")
print(f"Total Columns Kept: {len(df_rc.columns)}")


print(df_rc[['Co_Ref', 'Call_Date', 'Call_Length_Score', 'Membership_Renewal_Decision']].head())

Cleaning Complete.
Total Unique Calls: 127307
Total Columns Kept: 45
   Co_Ref  Call_Date  Call_Length_Score Membership_Renewal_Decision
0  AA0584 2024-05-01                  2             Pending/Unknown
1  AA0641 2024-11-11                  3             Pending/Unknown
2  AA0784 2026-01-06                  1                   Cancelled
3  AA0784 2026-01-14                  1                   Cancelled
4  AA0784 2026-01-16                  1                   Cancelled

type checking

In [32]:
df_rc.dtypes

Co_Ref                                                       object
Call_Date                                            datetime64[ns]
Call_ID                                                       int64
Call_Direction                                               object
Churn_Category                                               object
Complaint_Category                                           object
Customer_Reaction_Category                                   object
Agent_Renewal_Pitch_Category                                 object
Customer_Renewal_Response_Category                           object
Agent_Response_Category                                      object
Membership_Renewal_Decision                                  object
Serious_Complaint                                             int64
Other_Complaint                                              object
Discussion_on_Price_Increase                                  int64
Renewal_Impact_Due_to_Price_Increase                         object
Discount_or_Waiver_Requested                                 object
Call_Reschedule_Request                                      object
Agent_Flagged_Membership_Status_Alert                        object
Agent_Renewal_Initiation                                     object
Explicit_Competitor_Mention                                   int64
Explicit_Switching_Intent                                     int64
Mentioned_Competitors                                        object
Price_Switching_Mentioned                                    object
Competitor_Value_Comparison                                  object
Competitor_Benefits_Mentioned                                object
Topic_Introduced_By                                          object
Percentage_Price_Increase_Mentioned                          object
Monetary_Price_Increase_Mentioned                            object
Price_Range_Mentioned                                        object
Customer_Asked_For_Justification                             object
Customer_Response                                            object
Discount_Offered                                              int64
Justification_Category                                       object
Reason_For_Renewal_Category                                  object
Agent_Response_To_Cancel_Category                            object
Argument_That_Convinced_Customer_to_Stay_Category            object
Analysed_Call                                                object
Call_Number                                                   int64
Call_Year                                                     int64
discount_reason                                              object
asked_for_discount                                            int64
Analysed_Call_Status                                         object
has_desired_to_cancel                                         int64
cancel_reason                                                object
Call_Length_Score                                             int64
dtype: object

In [33]:
# 1. Get a list of all columns that are object type
object_columns = df_rc.select_dtypes(include=['object']).columns

# 2. Loop through them and print unique values
for col in object_columns:
    unique_count = df_rc[col].nunique()
    
    print(f"--- Column: {col} ({unique_count} unique values) ---")
    
    # If there are fewer than 20 unique values, show them all
    if unique_count < 20:
        print(df_rc[col].unique())
    # If there are many, just show the top 5 to see the format
    else:
        print(f"Top 5 values: {df_rc[col].value_counts().head(5).index.tolist()}")
    print("\n")

--- Column: Co_Ref (36303 unique values) ---
Top 5 values: ['AD1657', 'UW3387', 'ZF9958', 'XG1277', 'YT5805']


--- Column: Call_Direction (2 unique values) ---
['outbound' 'inbound']


--- Column: Churn_Category (18 unique values) ---
['Not Mentioned' 'Unnecessary / Not needed'
 'Switch / Change / Alternate Provider'
 'Financial struggles / Business Problems'
 'Left / Not with client anymore' 'Lack of Benefits'
 'Cost / Price / Too expensive' 'Others' 'Customer Service / Support'
 'Payment / Invoice Issue' 'Accreditation / Certification'
 'Client Requirement' 'Process Issues' 'Value of service'
 'Auto / Automatic' 'Account Information' 'Audit'
 'Portal / Technical Issues']


--- Column: Complaint_Category (22 unique values) ---
Top 5 values: ['Not Mentioned', 'Price Increase / Rise and Value', 'Accreditation and Certification', 'Payment Issues', 'Process and Auto-Renewal Issues']


--- Column: Customer_Reaction_Category (13 unique values) ---
['Not Mentioned' 'Clarification / Justification / Inquiry'
 'Agreement / Acceptance / Acknowledgement' 'Negotiation' 'Hesitation'
 'Dissatisfaction / Concern / Complaint / Frustration'
 'Financial Hardship / Struggle' 'Customer Retention' 'Discount / Offer'
 'Payment / Billing' 'Cancellation' 'Other' 'Value']


--- Column: Agent_Renewal_Pitch_Category (18 unique values) ---
['Not Mentioned' 'Discussion / Introduction / Inquiry'
 'Payment and Billings / Invoice' 'Expiration / Due' 'Annual'
 'Auto / Automatic' 'Assessment' 'Benefits'
 'Accreditation and Certification' 'Price and Cost' 'Audit'
 'Cancellation / Termination / Non-Renewal / Closure'
 'Discounts and Offers' 'Packages and Schemes'
 'Customer Service / Support' 'Insurance' 'Issues and Problems' 'Others']


--- Column: Customer_Renewal_Response_Category (20 unique values) ---
Top 5 values: ['Not Mentioned', 'Agreement', 'Payments and Billings / Invoice', 'Communication', 'Confusion / Uncertainty / Hesitation']


--- Column: Agent_Response_Category (20 unique values) ---
Top 5 values: ['Not Mentioned', 'Payment', 'Customer Communication', 'Confirmation / Acceptance / Agreement', 'Customer Service / Support']


--- Column: Membership_Renewal_Decision (3 unique values) ---
['Pending/Unknown' 'Cancelled' 'Renewed']


--- Column: Other_Complaint (4 unique values) ---
[0 'No' 'Yes' 'Yes/No']


--- Column: Renewal_Impact_Due_to_Price_Increase (19 unique values) ---
[0 'No' 'Yes'
 'Yes (the customer mentioned that they cannot renew due to financial reasons)'
 "Yes (The customer mentioned that they don't think they're going to be continuing with the membership and later stated that they would rather just cancel it.)"
 'Not applicable'
 'Yes (The customer had already initiated the cancellation of their membership)'
 '[Yes/No]'
 'Yes (The customer mentioned they are not going to go ahead with the membership at the moment, which can be inferred as not renewing)'
 '**No**'
 'Yes (the customer mentioned they were questioning whether to sign up again because they only have one person who requires it)'
 "Yes (The customer's account is being cancelled, but it's not explicitly stated that it's due to a price increase, however, the context implies that the customer is not renewing)"
 'Yes (the customer mentioned that they cannot afford to pay £500 for the service and decided not to renew their membership)'
 'Yes (due to other reasons, not price increase)'
 'Yes (the customer is calling to inquire about not renewing their membership)'
 'Yes, the customer is considering not renewing due to lack of perceived value, not specifically because of a price increase.'
 "Yes (the customer mentioned that if they can't offer any reduction in price, they'd be looking elsewhere)"
 'Yes, the customer decided not to renew their membership due to financial difficulties, not a price increase.'
 'Yes, the customer mentioned that they are not renewing this year, but it was not explicitly stated that this decision was due to a price increase, as no price increase was mentioned.']


--- Column: Discount_or_Waiver_Requested (24 unique values) ---
Top 5 values: [0, 'No', 'Yes', '[Yes/No]', 'Not applicable']


--- Column: Call_Reschedule_Request (4 unique values) ---
[0 'No' 'Yes' 'Not Applicable']


--- Column: Agent_Flagged_Membership_Status_Alert (4 unique values) ---
[0 'No' 'Yes' 'Not Applicable']


--- Column: Agent_Renewal_Initiation (4 unique values) ---
[0 'No' 'Yes' 'Not Applicable']


--- Column: Mentioned_Competitors (10 unique values) ---
['Not Mentioned' 'No' 'Yes' 'XXXX'
 '5% price increase, suggesting they may be considering other options.'
 'UNAVAILABLE' '59 plus VAT' '[No]' ':' '64 a year."']


--- Column: Price_Switching_Mentioned (7 unique values) ---
[0 'No' 'Yes'
 'No - Q9: Not Applicable - Q10: Not Applicable - Q11: Not Discussed'
 'No - Q9: Not Applicable - Q10: Not Applicable - Q11: Not Applicable' '"'
 '[Yes/No]']


--- Column: Competitor_Value_Comparison (59 unique values) ---
Top 5 values: [0, 'Not Applicable', 'Not Discussed', 'Better Value', 'Similar Value']


--- Column: Competitor_Benefits_Mentioned (277 unique values) ---
Top 5 values: [0, 'Not Applicable', 'Not Discussed', 'Discounts', 'Better service']


--- Column: Topic_Introduced_By (4 unique values) ---
['Not Mentioned' 'Not Discussed' 'Customer' 'Agent']


--- Column: Percentage_Price_Increase_Mentioned (4 unique values) ---
[0 'No' 'Not Discussed' 'Yes']


--- Column: Monetary_Price_Increase_Mentioned (4 unique values) ---
[0 'No' 'Not Discussed' 'Yes']


--- Column: Price_Range_Mentioned (2363 unique values) ---
Top 5 values: [0, 'Not Discussed', '£579 to £599', '£749 to £799', '£599 to £499']


--- Column: Customer_Asked_For_Justification (4 unique values) ---
[0 'No' 'Yes' 'Not Discussed']


--- Column: Customer_Response (5 unique values) ---
['Not Mentioned' 'Neutral' 'Not Discussed' 'Positive' 'Negative']


--- Column: Justification_Category (30 unique values) ---
Top 5 values: ['Not Mentioned', 'Other (misidentified)', 'Value of product', 'Incentive offered', 'External factors']


--- Column: Reason_For_Renewal_Category (23 unique values) ---
Top 5 values: ['Not Mentioned', 'Incentive / support offered', 'Value of product', 'Price adjustments increase', 'Payment terms / renewal conditions']


--- Column: Agent_Response_To_Cancel_Category (22 unique values) ---
Top 5 values: ['Not Mentioned', 'Incentive / support offered', 'Other (misidentified)', 'Offers / Incentives', 'Accreditation / Compliance']


--- Column: Argument_That_Convinced_Customer_to_Stay_Category (17 unique values) ---
['Not Mentioned' 'Incentive / support offered' 'Value of product'
 'Strong client relationship' 'Financial Incentives / Cost-Effectiveness'
 'Non-Renewal / Cancellation' 'Other (misidentified)'
 'Payment terms / renewal conditions' 'Cancellation'
 'Accreditation / Compliance / Trust' 'Communication / Relationships'
 'Payment convenience' 'Value Proposition / Benefits'
 'Business Growth / Opportunities' 'Customer Service / Support'
 'Contract / Renewal Processes' 'Payment Transparency / Flexibility']


--- Column: Analysed_Call (2 unique values) ---
['No Analysis Available' 1.0]


--- Column: discount_reason (12 unique values) ---
['No Request'
 'the customer did not ask for a discount or waiver to the price increase'
 'the agent offers a discounted price as a goodwill gesture'
 'Customer inquired about reducing the bill and had a previously applied discount re-applied'
 'the customer implies that they are looking for a better price and the agent offers a discount'
 'The customer is seeking a discount.'
 'the agent offers a discount to the customer'
 'the customer did not ask for a discount or waiver to the price increase, but the agent offered a £ saving on the original price'
 'the customer did not ask for a discount or waiver to a price increase, but the agent offered a discount'
 'although a discount was offered'
 'the customer asked if the price was the best they could do, implying a request for a discount or waiver'
 'the customer asked for a reduction on the bill']


--- Column: Analysed_Call_Status (2 unique values) ---
['Not Analysed' 'Other']


--- Column: cancel_reason (259 unique values) ---
Top 5 values: ['No Reason Given', 'initially', 'implied, but not explicitly stated', 'Not Discussed', 'implied, not explicitly stated']

Cleaning of prefixes found

In [34]:
import numpy as np

# A function to clean the prefixes and brackets
def clean_string_logic(val):
    val = str(val).strip().lower()
    if val in ['no', '[no]', 'prompt 3: no', 'prompt 4:', 'xxxx', 'unavailable', 'nan', '0', '0.0', '**no**']:
        return 'No'
    if val in ['yes', '[yes]', '1', '1.0']:
        return 'Yes'
    if 'yes/no' in val or 'not discussed' in val or 'not applicable' in val:
        return 'Unknown'
    return val.capitalize()

flag_cols = ['Explicit_Competitor_Mention', 'Explicit_Switching_Intent', 'Serious_Complaint', 'Discussion_on_Price_Increase']
for col in flag_cols:
    df_rc[col] = df_rc[col].apply(clean_string_logic)

Giving type Category to categorical columns

In [35]:
cat_cols = [
    'Call_Direction', 'Churn_Category', 'Complaint_Category', 
    'Customer_Reaction_Category', 'Agent_Renewal_Pitch_Category',
    'Membership_Renewal_Decision', 'Analysed_Call_Status'
]

for col in cat_cols:
    df_rc[col] = df_rc[col].astype('category')

In [36]:
df_rc.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 127307 entries, 0 to 127306
Data columns (total 45 columns):
 #   Column                                             Non-Null Count   Dtype
---  ------                                             --------------   -----
 0   Co_Ref                                             127307 non-null  object
 1   Call_Date                                          127307 non-null  datetime64[ns]
 2   Call_ID                                            127307 non-null  int64
 3   Call_Direction                                     127307 non-null  category
 4   Churn_Category                                     127307 non-null  category
 5   Complaint_Category                                 127307 non-null  category
 6   Customer_Reaction_Category                         127307 non-null  category
 7   Agent_Renewal_Pitch_Category                       127307 non-null  category
 8   Customer_Renewal_Response_Category                 127307 non-null  object
 9   Agent_Response_Category                            127307 non-null  object
 10  Membership_Renewal_Decision                        127307 non-null  category
 11  Serious_Complaint                                  127307 non-null  object
 12  Other_Complaint                                    127307 non-null  object
 13  Discussion_on_Price_Increase                       127307 non-null  object
 14  Renewal_Impact_Due_to_Price_Increase               127307 non-null  object
 15  Discount_or_Waiver_Requested                       127307 non-null  object
 16  Call_Reschedule_Request                            127307 non-null  object
 17  Agent_Flagged_Membership_Status_Alert              127307 non-null  object
 18  Agent_Renewal_Initiation                           127307 non-null  object
 19  Explicit_Competitor_Mention                        127307 non-null  object
 20  Explicit_Switching_Intent                          127307 non-null  object
 21  Mentioned_Competitors                              127307 non-null  object
 22  Price_Switching_Mentioned                          127307 non-null  object
 23  Competitor_Value_Comparison                        127307 non-null  object
 24  Competitor_Benefits_Mentioned                      127307 non-null  object
 25  Topic_Introduced_By                                127307 non-null  object
 26  Percentage_Price_Increase_Mentioned                127307 non-null  object
 27  Monetary_Price_Increase_Mentioned                  127307 non-null  object
 28  Price_Range_Mentioned                              127307 non-null  object
 29  Customer_Asked_For_Justification                   127307 non-null  object
 30  Customer_Response                                  127307 non-null  object
 31  Discount_Offered                                   127307 non-null  int64
 32  Justification_Category                             127307 non-null  object
 33  Reason_For_Renewal_Category                        127307 non-null  object
 34  Agent_Response_To_Cancel_Category                  127307 non-null  object
 35  Argument_That_Convinced_Customer_to_Stay_Category  127307 non-null  object
 36  Analysed_Call                                      127307 non-null  object
 37  Call_Number                                        127307 non-null  int64
 38  Call_Year                                          127307 non-null  int64
 39  discount_reason                                    127307 non-null  object
 40  asked_for_discount                                 127307 non-null  int64
 41  Analysed_Call_Status                               127307 non-null  category
 42  has_desired_to_cancel                              127307 non-null  int64
 43  cancel_reason                                      127307 non-null  object
 44  Call_Length_Score                                  127307 non-null  int64
dtypes: category(7), datetime64[ns](1), int64(7), object(30)
memory usage: 37.8+ MB

In [37]:
df_rc.head(10)

,Co_Ref,Call_Date,Call_ID,Call_Direction,Churn_Category,Complaint_Category,Customer_Reaction_Category,Agent_Renewal_Pitch_Category,Customer_Renewal_Response_Category,Agent_Response_Category,...,Argument_That_Convinced_Customer_to_Stay_Category,Analysed_Call,Call_Number,Call_Year,discount_reason,asked_for_discount,Analysed_Call_Status,has_desired_to_cancel,cancel_reason,Call_Length_Score
0,AA0584,2024-05-01,507000000000,outbound,Not Mentioned,Not Mentioned,Not Mentioned,Not Mentioned,Not Mentioned,Not Mentioned,...,Not Mentioned,No Analysis Available,2,2024,No Request,1,Not Analysed,0,No Reason Given,2
1,AA0641,2024-11-11,590000000000,outbound,Not Mentioned,Not Mentioned,Not Mentioned,Not Mentioned,Not Mentioned,Not Mentioned,...,Not Mentioned,No Analysis Available,3,2024,No Request,1,Not Analysed,0,No Reason Given,3
2,AA0784,2026-01-06,692000000000,outbound,Not Mentioned,Not Mentioned,Not Mentioned,Not Mentioned,Communication,Customer Communication,...,Not Mentioned,1.0,1,2026,No Request,1,Other,0,No Reason Given,1
3,AA0784,2026-01-14,692000000000,outbound,Not Mentioned,Not Mentioned,Not Mentioned,Not Mentioned,Not Mentioned,Not Mentioned,...,Not Mentioned,1.0,2,2026,No Request,1,Other,0,No Reason Given,1
4,AA0784,2026-01-16,692000000000,outbound,Not Mentioned,Not Mentioned,Not Mentioned,Not Mentioned,Communication,Customer Communication,...,Not Mentioned,1.0,3,2026,No Request,1,Other,0,No Reason Given,1
5,AA0794,2025-09-24,194000000000,outbound,Not Mentioned,Not Mentioned,Not Mentioned,Not Mentioned,Not Mentioned,Not Mentioned,...,Not Mentioned,1.0,1,2025,No Request,1,Other,0,No Reason Given,1
6,AA0794,2025-10-03,684000000000,outbound,Not Mentioned,Not Mentioned,Not Mentioned,Discussion / Introduction / Inquiry,Confusion / Uncertainty / Hesitation,Customer Communication,...,Not Mentioned,1.0,2,2025,No Request,1,Other,0,No Reason Given,1
7,AA0794,2025-10-07,684000000000,outbound,Not Mentioned,Not Mentioned,Not Mentioned,Not Mentioned,Not Mentioned,Not Mentioned,...,Not Mentioned,No Analysis Available,3,2025,No Request,1,Not Analysed,0,No Reason Given,1
8,AA0794,2025-10-08,685000000000,outbound,Not Mentioned,Not Mentioned,Not Mentioned,Discussion / Introduction / Inquiry,Communication,Confirmation / Acceptance / Agreement,...,Not Mentioned,1.0,4,2025,No Request,1,Other,0,No Reason Given,1
9,AA0794,2025-10-14,685000000000,outbound,Not Mentioned,Not Mentioned,Not Mentioned,Not Mentioned,Not Mentioned,Not Mentioned,...,Not Mentioned,No Analysis Available,5,2025,No Request,1,Not Analysed,0,No Reason Given,1

Cleaning the data values, applying the binary logic

In [38]:
def clean_binary_logic(val):
    # Preserve missing values so downstream harmonize_to_labels sees them
    if pd.isna(val):
        return val
    
    s = str(val).strip().lower().replace('*', '').replace('[', '').replace(']', '')
    
    # If already standardized Yes/No, keep as string for harmonize_to_labels
    if s in ['yes', 'no']:
        return s.title()
    
    # Map explicit true-like values to 'Yes'
    if s in ['1', '1.0', 'true']:
        return 'Yes'
    
    # Map explicit false-like values to 'No'
    if s in ['0', '0.0', 'false']:
        return 'No'
    
    # Everything else -> 'No'
    return 'No'

flag_columns = [
    'Serious_Complaint', 'Other_Complaint', 'Discussion_on_Price_Increase', 
    'Discount_or_Waiver_Requested', 'Call_Reschedule_Request', 
    'Explicit_Competitor_Mention', 'Explicit_Switching_Intent',
    'asked_for_discount', 'has_desired_to_cancel', 'Discount_Offered'
]

for col in flag_columns:
    if col in df_rc.columns:
        df_rc[col] = df_rc[col].apply(clean_binary_logic)

Filling not mentioned for categorical columns where null values are present

In [39]:
target_cols = [
    'Complaint_Category', 
    'Customer_Reaction_Category', 
    'Agent_Renewal_Pitch_Category', 
    'Customer_Renewal_Response_Category', 
    'Agent_Response_Category'
]

# Fill actual nulls so they aren't invisible to the model
df_rc[target_cols] = df_rc[target_cols].fillna('Not Mentioned')

segregating values for Complaint_Category

In [40]:
# Create a 'Has_Complaint' flag: 1 if they complained, 0 if 'Not Mentioned'
df_rc['Has_Complaint'] = df_rc['Complaint_Category'].apply(lambda x: 0 if x == 'Not Mentioned' else 1)

# Create a 'Negative_Reaction' flag
negative_terms = ['Dissatisfaction', 'Cancellation', 'Financial Hardship', 'Negotiation']
df_rc['Has_Negative_Reaction'] = df_rc['Customer_Reaction_Category'].apply(
    lambda x: 1 if (pd.notna(x) and str(x).strip() in negative_terms) else 0
)

Found blanks, fixing the blanks

In [41]:
# List of columns that only appear when there is a 'Conflict' or 'Save'
conditional_cols = [
    'Justification_Category', 
    'Reason_For_Renewal_Category', 
    'Agent_Response_To_Cancel_Category', 
    'Argument_That_Convinced_Customer_to_Stay_Category'
]

# Fill blanks with 'Not Applicable'
# This ensures they are treated as 'Successful/No Problem' cases
df_rc[conditional_cols] = df_rc[conditional_cols].fillna('Not Applicable')

# Also replace any existing 'Not Mentioned' with 'Not Applicable' for consistency
df_rc[conditional_cols] = df_rc[conditional_cols].replace('Not Mentioned', 'Not Applicable')

generalizing values in columns to no, yes

In [42]:

# The Harmonizer Function
def harmonize_to_labels(val):
    if pd.isna(val) or str(val).strip() == "" or str(val).lower() == 'nan':
        return "Not Mentioned"
    
    s = str(val).strip().lower().replace('*', '').replace('[', '').replace(']', '')
    
    # Map to "Yes"
    if s in ['yes', '1', '1.0', 'true', 'won', 'renewed', 'renew']:
        return "Yes"
    
    # Map to "No"
    if s in ['no', '0', '0.0', 'false']:
        return "No"
    
    # If it's a specific category, keep it as is
    return str(val).strip()

cols_to_transform = []

for col in df_rc.columns:
    # Skip ID, Date, and numeric columns like Year or Call_Number
    if col in ['Co_Ref', 'Call_Date', 'Call_ID', 'Call_Year', 'Call_Number', 'Call_Length_Score']:
        continue
        
    # Get unique values, ignoring NaNs, and clean them
    unique_vals = df_rc[col].dropna().unique()
    clean_uniques = {str(v).strip().lower().replace('*', '').replace('[', '').replace(']', '') for v in unique_vals}
    
    # Identify if the column is primarily Yes/No/0/1 signals
    binary_signals = {'yes', 'no', '0', '1', '1.0', '0.0', 'true', 'false', 'not discussed', 'not applicable'}
    # Require either a full subset or majority overlap with binary_signals
    overlap = clean_uniques & binary_signals
    if clean_uniques.issubset(binary_signals) or (len(overlap) > 0 and len(overlap) / len(clean_uniques) >= 0.5):
        cols_to_transform.append(col)

# Apply the transformation to all identified columns
for col in cols_to_transform:
    df_rc[col] = df_rc[col].apply(harmonize_to_labels)

for col in df_rc.select_dtypes(include=["category"]).columns:
    if "Not Mentioned" not in df_rc[col].cat.categories:
        df_rc[col] = df_rc[col].cat.add_categories("Not Mentioned")
df_rc = df_rc.fillna("Not Mentioned")

print(f"Cleaned {len(cols_to_transform)} columns to Yes/No/Not Mentioned format.")
print(f"Columns transformed: {cols_to_transform}")

Cleaned 18 columns to Yes/No/Not Mentioned format.
Columns transformed: ['Serious_Complaint', 'Other_Complaint', 'Discussion_on_Price_Increase', 'Discount_or_Waiver_Requested', 'Call_Reschedule_Request', 'Agent_Flagged_Membership_Status_Alert', 'Agent_Renewal_Initiation', 'Explicit_Competitor_Mention', 'Explicit_Switching_Intent', 'Percentage_Price_Increase_Mentioned', 'Monetary_Price_Increase_Mentioned', 'Customer_Asked_For_Justification', 'Discount_Offered', 'Analysed_Call', 'asked_for_discount', 'has_desired_to_cancel', 'Has_Complaint', 'Has_Negative_Reaction']

Handling Nulls, NaNs etc for catgeorical columns

In [43]:
problem_cols = [
    'Renewal_Impact_Due_to_Price_Increase', 
    'Price_Switching_Mentioned', 
    'Competitor_Value_Comparison', 
    'Competitor_Benefits_Mentioned', 
    'Price_Range_Mentioned'
]

def final_cleanup(val):
    # Handle Nulls/Nans
    if pd.isna(val):
        return "Not Mentioned"
    
    # Standardize string for checking
    s = str(val).strip().lower()
    
    # If the value is a '0' variant, turn it into 'Not Mentioned'
    if s in ['0', '0.0', 'none', 'nan', 'not discussed', 'not applicable']:
        return "Not Mentioned"
    
    # For 'Price_Switching_Mentioned' and 'Impact', handle No variants
    # If you prefer these to stay as 'No' instead of 'Not Mentioned'
    if s == 'no':
        return "No"
    
    # Keep the actual categories/descriptions (e.g., "Better Value", "£500")
    return str(val).strip()

for col in problem_cols:
    if col in df_rc.columns:
        df_rc[col] = df_rc[col].apply(final_cleanup)

In [44]:
df_rc.isnull().sum()

Co_Ref                                               0
Call_Date                                            0
Call_ID                                              0
Call_Direction                                       0
Churn_Category                                       0
Complaint_Category                                   0
Customer_Reaction_Category                           0
Agent_Renewal_Pitch_Category                         0
Customer_Renewal_Response_Category                   0
Agent_Response_Category                              0
Membership_Renewal_Decision                          0
Serious_Complaint                                    0
Other_Complaint                                      0
Discussion_on_Price_Increase                         0
Renewal_Impact_Due_to_Price_Increase                 0
Discount_or_Waiver_Requested                         0
Call_Reschedule_Request                              0
Agent_Flagged_Membership_Status_Alert                0
Agent_Renewal_Initiation                             0
Explicit_Competitor_Mention                          0
Explicit_Switching_Intent                            0
Mentioned_Competitors                                0
Price_Switching_Mentioned                            0
Competitor_Value_Comparison                          0
Competitor_Benefits_Mentioned                        0
Topic_Introduced_By                                  0
Percentage_Price_Increase_Mentioned                  0
Monetary_Price_Increase_Mentioned                    0
Price_Range_Mentioned                                0
Customer_Asked_For_Justification                     0
Customer_Response                                    0
Discount_Offered                                     0
Justification_Category                               0
Reason_For_Renewal_Category                          0
Agent_Response_To_Cancel_Category                    0
Argument_That_Convinced_Customer_to_Stay_Category    0
Analysed_Call                                        0
Call_Number                                          0
Call_Year                                            0
discount_reason                                      0
asked_for_discount                                   0
Analysed_Call_Status                                 0
has_desired_to_cancel                                0
cancel_reason                                        0
Call_Length_Score                                    0
Has_Complaint                                        0
Has_Negative_Reaction                                0
dtype: int64

Checking unique values for every column

In [45]:
# Loop through every column and print its unique values
for col in df_rc.columns:
    unique_values = df_rc[col].unique()
    
    print(f"--- Column: {col} ---")
    print(f"Total Unique Values: {len(unique_values)}")
    

    if len(unique_values) > 15:
        print(f"Sample Values: {list(unique_values[:10])}...")
    else:
        print(f"Values: {list(unique_values)}")
    
    print("-" * 40)

--- Column: Co_Ref ---
Total Unique Values: 36303
Sample Values: ['AA0584', 'AA0641', 'AA0784', 'AA0794', 'AA0882', 'AA0994', 'AA1155', 'AA1246', 'AA1392', 'AA1394']...
----------------------------------------
--- Column: Call_Date ---
Total Unique Values: 467
Sample Values: [Timestamp('2024-05-01 00:00:00'), Timestamp('2024-11-11 00:00:00'), Timestamp('2026-01-06 00:00:00'), Timestamp('2026-01-14 00:00:00'), Timestamp('2026-01-16 00:00:00'), Timestamp('2025-09-24 00:00:00'), Timestamp('2025-10-03 00:00:00'), Timestamp('2025-10-07 00:00:00'), Timestamp('2025-10-08 00:00:00'), Timestamp('2025-10-14 00:00:00')]...
----------------------------------------
--- Column: Call_ID ---
Total Unique Values: 53
Sample Values: [np.int64(507000000000), np.int64(590000000000), np.int64(692000000000), np.int64(194000000000), np.int64(684000000000), np.int64(685000000000), np.int64(682000000000), np.int64(512000000000), np.int64(593000000000), np.int64(594000000000)]...
----------------------------------------
--- Column: Call_Direction ---
Total Unique Values: 2
Values: ['outbound', 'inbound']
----------------------------------------
--- Column: Churn_Category ---
Total Unique Values: 18
Sample Values: ['Not Mentioned', 'Unnecessary / Not needed', 'Switch / Change / Alternate Provider', 'Financial struggles / Business Problems', 'Left / Not with client anymore', 'Lack of Benefits', 'Cost / Price / Too expensive', 'Others', 'Customer Service / Support', 'Payment / Invoice Issue']...
----------------------------------------
--- Column: Complaint_Category ---
Total Unique Values: 22
Sample Values: ['Not Mentioned', 'Process and Auto-Renewal Issues', 'Payment Issues', 'Login and Access', 'Portal and Technical Issues', 'Price Increase / Rise and Value', 'Account Information', 'Customer Service', 'Accreditation and Certification', 'Financial Hardship']...
----------------------------------------
--- Column: Customer_Reaction_Category ---
Total Unique Values: 13
Values: ['Not Mentioned', 'Clarification / Justification / Inquiry', 'Agreement / Acceptance / Acknowledgement', 'Negotiation', 'Hesitation', 'Dissatisfaction / Concern / Complaint / Frustration', 'Financial Hardship / Struggle', 'Customer Retention', 'Discount / Offer', 'Payment / Billing', 'Cancellation', 'Other', 'Value']
----------------------------------------
--- Column: Agent_Renewal_Pitch_Category ---
Total Unique Values: 18
Sample Values: ['Not Mentioned', 'Discussion / Introduction / Inquiry', 'Payment and Billings / Invoice', 'Expiration / Due', 'Annual', 'Auto / Automatic', 'Assessment', 'Benefits', 'Accreditation and Certification', 'Price and Cost']...
----------------------------------------
--- Column: Customer_Renewal_Response_Category ---
Total Unique Values: 20
Sample Values: ['Not Mentioned', 'Communication', 'Confusion / Uncertainty / Hesitation', 'Cancellation / Termination / Non-Renewal / Withdrawal', 'Agreement', 'Auto / Automatic', 'Package', 'Price and Cost', 'Payments and Billings / Invoice', 'Accreditation and Certification']...
----------------------------------------
--- Column: Agent_Response_Category ---
Total Unique Values: 20
Sample Values: ['Not Mentioned', 'Customer Communication', 'Confirmation / Acceptance / Agreement', 'Customer Service / Support', 'Account information', 'Auto / Automatic', 'Cancellation / Termination / Closure', 'Accreditation and Certification', 'Payment', 'Price and Cost']...
----------------------------------------
--- Column: Membership_Renewal_Decision ---
Total Unique Values: 3
Values: ['Pending/Unknown', 'Cancelled', 'Renewed']
----------------------------------------
--- Column: Serious_Complaint ---
Total Unique Values: 2
Values: ['No', 'Yes']
----------------------------------------
--- Column: Other_Complaint ---
Total Unique Values: 2
Values: ['No', 'Yes']
----------------------------------------
--- Column: Discussion_on_Price_Increase ---
Total Unique Values: 2
Values: ['No', 'Yes']
----------------------------------------
--- Column: Renewal_Impact_Due_to_Price_Increase ---
Total Unique Values: 18
Sample Values: ['Not Mentioned', 'No', 'Yes', 'Yes (the customer mentioned that they cannot renew due to financial reasons)', "Yes (The customer mentioned that they don't think they're going to be continuing with the membership and later stated that they would rather just cancel it.)", 'Yes (The customer had already initiated the cancellation of their membership)', '[Yes/No]', 'Yes (The customer mentioned they are not going to go ahead with the membership at the moment, which can be inferred as not renewing)', '**No**', 'Yes (the customer mentioned they were questioning whether to sign up again because they only have one person who requires it)']...
----------------------------------------
--- Column: Discount_or_Waiver_Requested ---
Total Unique Values: 2
Values: ['No', 'Yes']
----------------------------------------
--- Column: Call_Reschedule_Request ---
Total Unique Values: 2
Values: ['No', 'Yes']
----------------------------------------
--- Column: Agent_Flagged_Membership_Status_Alert ---
Total Unique Values: 3
Values: ['No', 'Yes', 'Not Applicable']
----------------------------------------
--- Column: Agent_Renewal_Initiation ---
Total Unique Values: 3
Values: ['No', 'Yes', 'Not Applicable']
----------------------------------------
--- Column: Explicit_Competitor_Mention ---
Total Unique Values: 2
Values: ['No', 'Yes']
----------------------------------------
--- Column: Explicit_Switching_Intent ---
Total Unique Values: 2
Values: ['No', 'Yes']
----------------------------------------
--- Column: Mentioned_Competitors ---
Total Unique Values: 10
Values: ['Not Mentioned', 'No', 'Yes', 'XXXX', '5% price increase, suggesting they may be considering other options.', 'UNAVAILABLE', '59 plus VAT', '[No]', ':', '64 a year."']
----------------------------------------
--- Column: Price_Switching_Mentioned ---
Total Unique Values: 7
Values: ['Not Mentioned', 'No', 'Yes', 'No - Q9: Not Applicable - Q10: Not Applicable - Q11: Not Discussed', 'No - Q9: Not Applicable - Q10: Not Applicable - Q11: Not Applicable', '"', '[Yes/No]']
----------------------------------------
--- Column: Competitor_Value_Comparison ---
Total Unique Values: 56
Sample Values: ['Not Mentioned', 'Better Value', 'Similar Value', 'Not Applicable (However, I will follow the instructions and provide a response) Similar Value', 'Not Applicable (However, I will provide an answer as per the instructions) Similar Value', '69 a year.', '69 plus VAT for the same service.', 'Not Applicable (Since the customer does not directly compare the value of the competitor)', 'Not Applicable (Since Q8 is No)', "00, and compares it to Safe Contractor's price."]...
----------------------------------------
--- Column: Competitor_Benefits_Mentioned ---
Total Unique Values: 273
Sample Values: ['Not Mentioned', 'Discounts', 'Offering', 'Better service, Discounts', 'Better service', 'Discounts, Offering', 'Reduced cost', 'Better pricing', 'Similar accreditation', 'Better Service']...
----------------------------------------
--- Column: Topic_Introduced_By ---
Total Unique Values: 4
Values: ['Not Mentioned', 'Not Discussed', 'Customer', 'Agent']
----------------------------------------
--- Column: Percentage_Price_Increase_Mentioned ---
Total Unique Values: 3
Values: ['No', 'Not Discussed', 'Yes']
----------------------------------------
--- Column: Monetary_Price_Increase_Mentioned ---
Total Unique Values: 3
Values: ['No', 'Not Discussed', 'Yes']
----------------------------------------
--- Column: Price_Range_Mentioned ---
Total Unique Values: 2362
Sample Values: ['Not Mentioned', '£949 to £958.80', '£799 to £666.20', '£799 to £999', '£579 to £599', '£478.80 to £718', '£1,309 to £704', '£69 to £1,079', '£2,249 to £3,439', '£3,400 to £2,800']...
----------------------------------------
--- Column: Customer_Asked_For_Justification ---
Total Unique Values: 3
Values: ['No', 'Yes', 'Not Discussed']
----------------------------------------
--- Column: Customer_Response ---
Total Unique Values: 5
Values: ['Not Mentioned', 'Neutral', 'Not Discussed', 'Positive', 'Negative']
----------------------------------------
--- Column: Discount_Offered ---
Total Unique Values: 2
Values: ['No', 'Yes']
----------------------------------------
--- Column: Justification_Category ---
Total Unique Values: 30
Sample Values: ['Not Applicable', 'Payment terms / renewal conditions', 'Change in band', 'External factors', 'Incentive offered', 'Other (misidentified)', 'Pricing Adjustments decrease', 'Value of product', 'Discount removal / VAT inclusion', 'Change in package']...
----------------------------------------
--- Column: Reason_For_Renewal_Category ---
Total Unique Values: 23
Sample Values: ['Not Applicable', 'Price adjustments decrease', 'Strong client relationship', 'Other (misidentified)', 'Value of product', 'Incentive / support offered', 'Price adjustments increase', 'Payment terms / renewal conditions', 'Pricing / Cost / Payments', 'Accreditation / Compliance']...
----------------------------------------
--- Column: Agent_Response_To_Cancel_Category ---
Total Unique Values: 22
Sample Values: ['Not Applicable', 'Value of product', 'Payment convenience', 'Incentive / support offered', 'Adjusted account or package', 'Payment / Billing options', 'Membership / Partnerships benefits', 'Offers / Incentives', 'Other (misidentified)', 'Negotiation / Review']...
----------------------------------------
--- Column: Argument_That_Convinced_Customer_to_Stay_Category ---
Total Unique Values: 17
Sample Values: ['Not Applicable', 'Incentive / support offered', 'Value of product', 'Strong client relationship', 'Financial Incentives / Cost-Effectiveness', 'Non-Renewal / Cancellation', 'Other (misidentified)', 'Payment terms / renewal conditions', 'Cancellation', 'Accreditation / Compliance / Trust']...
----------------------------------------
--- Column: Analysed_Call ---
Total Unique Values: 2
Values: ['No Analysis Available', 'Yes']
----------------------------------------
--- Column: Call_Number ---
Total Unique Values: 181
Sample Values: [np.int64(2), np.int64(3), np.int64(1), np.int64(4), np.int64(5), np.int64(6), np.int64(7), np.int64(8), np.int64(9), np.int64(10)]...
----------------------------------------
--- Column: Call_Year ---
Total Unique Values: 3
Values: [np.int64(2024), np.int64(2026), np.int64(2025)]
----------------------------------------
--- Column: discount_reason ---
Total Unique Values: 12
Values: ['No Request', 'the customer did not ask for a discount or waiver to the price increase', 'the agent offers a discounted price as a goodwill gesture', 'Customer inquired about reducing the bill and had a previously applied discount re-applied', 'the customer implies that they are looking for a better price and the agent offers a discount', 'The customer is seeking a discount.', 'the agent offers a discount to the customer', 'the customer did not ask for a discount or waiver to the price increase, but the agent offered a £ saving on the original price', 'the customer did not ask for a discount or waiver to a price increase, but the agent offered a discount', 'although a discount was offered', 'the customer asked if the price was the best they could do, implying a request for a discount or waiver', 'the customer asked for a reduction on the bill']
----------------------------------------
--- Column: asked_for_discount ---
Total Unique Values: 1
Values: ['Yes']
----------------------------------------
--- Column: Analysed_Call_Status ---
Total Unique Values: 2
Values: ['Not Analysed', 'Other']
----------------------------------------
--- Column: has_desired_to_cancel ---
Total Unique Values: 1
Values: ['No']
----------------------------------------
--- Column: cancel_reason ---
Total Unique Values: 259
Sample Values: ['No Reason Given', 'not explicitly stated, but the contractor did not commit to renewing', 'initially, but later decided to renew', 'initially', 'initially, but later decided to review and possibly renew', "initially due to financial difficulties, but considering renewal after the agent's offer", 'initially, but later undecided', 'implied, as the customer did not commit to renewal and ended the call to consider', 'considering switching to Chas Elite', 'implied, as the contractor mentioned Stephen was deliberating and might drop it']...
----------------------------------------
--- Column: Call_Length_Score ---
Total Unique Values: 16
Sample Values: [np.int64(2), np.int64(3), np.int64(1), np.int64(4), np.int64(5), np.int64(6), np.int64(7), np.int64(8), np.int64(13), np.int64(10)]...
----------------------------------------
--- Column: Has_Complaint ---
Total Unique Values: 2
Values: ['No', 'Yes']
----------------------------------------
--- Column: Has_Negative_Reaction ---
Total Unique Values: 2
Values: ['No', 'Yes']
----------------------------------------

Cleaning up noise in the data

In [46]:
# List of columns that still have messy sentences or noise
complex_cols = [
    'Renewal_Impact_Due_to_Price_Increase', 
    'Mentioned_Competitors', 
    'Price_Switching_Mentioned'
]

def final_label_cleaner(val):
    if pd.isna(val) or str(val).strip() == "":
        return "Not Mentioned"
    
    s = str(val).strip().lower().replace('*', '').replace('[', '').replace(']', '')
    
    # 1. Check noise/unknown values FIRST
    noise_values = ['not mentioned', 'not applicable', 'unknown', 'xxxx',
                    'unavailable', 'nan', ':', '"', 'yes/no']
    if s in noise_values:
        return "Not Mentioned"
    
    # 2. Explicit No
    if s.startswith('no') or s in ['false', '0', '0.0']:
        return "No"
    
    # 3. Explicit Yes -- token-based, NOT length-based
    if s in ['yes', 'true', '1', '1.0'] or s.startswith('yes'):
        return "Yes"
    
    # 4. Strings containing digits (e.g., price ranges) -> Yes
    if any(char.isdigit() for char in s):
        return "Yes"
    
    # 5. Anything else -> Not Mentioned (NO length heuristic)
    return "Not Mentioned"
for col in complex_cols:
    if col in df_rc.columns:
        df_rc[col] = df_rc[col].apply(final_label_cleaner)

for col in complex_cols:
    print(f"Cleaned {col}: {df_rc[col].unique()}")

Cleaned Renewal_Impact_Due_to_Price_Increase: ['Not Mentioned' 'No' 'Yes']
Cleaned Mentioned_Competitors: ['Not Mentioned' 'No' 'Yes']
Cleaned Price_Switching_Mentioned: ['Not Mentioned' 'No' 'Yes']

Applying uniformity to values

In [ ]:

df_rc = df_rc.replace('Not Discussed', 'Not Mentioned')

df_rc['Customer_Response'] = df_rc['Customer_Response'].replace(['Neutral', 'Positive', 'Negative'], 'Yes')

df_rc['Analysed_Call'] = df_rc['Analysed_Call'].apply(
    lambda x: 'Yes' if str(x).lower() == 'yes' else 'No'
)

def handle_comparison(val):
    s = str(val).strip().lower()
    if s in ['not mentioned', 'not applicable', 'no', '0', '0.0']:
        return "Not Mentioned"
    return "Yes" # Captures 'Better Value', 'Similar Value', and specific price quotes

df_rc['Competitor_Value_Comparison'] = df_rc['Competitor_Value_Comparison'].apply(handle_comparison)

final_fix_cols = ['Analysed_Call_Status', 'has_desired_to_cancel', 'asked_for_discount', 'Topic_Introduced_By']
for col in final_fix_cols:
    if col in df_rc.columns:
        df_rc[col] = df_rc[col].fillna('Not Mentioned')

Combining columns with same values

In [ ]:

# Drop non-predictive columns ONLY (keep signal columns for aggregation)
cols_to_drop = ['Analysed_Call_Status', 'Analysed_Call']
df_rc = df_rc.drop(columns=[c for c in cols_to_drop if c in df_rc.columns])

print(f"Dropped {len(cols_to_drop)} redundant columns. Friction score computed post-aggregation.")

Dropped 2 redundant columns. Friction score computed post-aggregation.

In [ ]:


flag_cols = [
    'Serious_Complaint', 'Other_Complaint', 'Discussion_on_Price_Increase',
    'Discount_or_Waiver_Requested', 'Call_Reschedule_Request', 'Explicit_Competitor_Mention',
    'Explicit_Switching_Intent', 'Discount_Offered', 'asked_for_discount', 
    'has_desired_to_cancel', 'Has_Complaint', 'Has_Negative_Reaction'
]


cat_cols = [
    'Complaint_Category', 'Customer_Reaction_Category', 'Agent_Renewal_Pitch_Category',
    'Customer_Renewal_Response_Category', 'Agent_Response_Category', 'Membership_Renewal_Decision',
    'Justification_Category', 'cancel_reason', 'discount_reason'
]


def aggregate_text(series):
    # Remove 'Not Mentioned' and duplicates before joining
    unique_vals = [str(x) for x in series.unique() if str(x) not in ['Not Mentioned', 'Not Applicable', '0', 'nan']]
    return "; ".join(unique_vals) if unique_vals else "Not Mentioned"

agg_map = {
    'Call_Date': 'max',          # Use the date of the most recent call
    'Call_Length_Score': 'mean',  # Average engagement
    'Call_Number': 'count'       # Total number of interactions/fragments
}

# Add Flags (use max: 'Yes' > 'No' > 'Not Mentioned')
for col in flag_cols:
    if col in df_rc.columns:
        agg_map[col] = 'max'

# Add Categories (Join strings)
for col in cat_cols:
    if col in df_rc.columns:
        agg_map[col] = aggregate_text


df_rc_final = df_rc.groupby(['Co_Ref', 'Call_Year']).agg(agg_map).reset_index()


def calculate_friction(row):
    score = 0
    if row.get('Serious_Complaint') == 'Yes': score += 2
    if row.get('Explicit_Switching_Intent') == 'Yes': score += 3
    if row.get('Has_Complaint') == 'Yes': score += 1
    return score

df_rc_final['Interaction_Friction_Score'] = df_rc_final.apply(calculate_friction, axis=1)

print(f"Success! Data squashed from {len(df_rc)} rows to {len(df_rc_final)} unique customer-years.")

Success! Data squashed from 127307 rows to 55038 unique customer-years.

Saving the cleaned data to a csv file for further processes.

In [ ]:
save_path = project_root / "data" / "processed"

# Create the folder if it doesn't exist yet
save_path.mkdir(parents=True, exist_ok=True)

# Save the file
df_rc.to_csv(save_path / "cleaned_renewal_calls.csv", index=False)

print(f"File successfully saved to: {save_path}")

File successfully saved to: c:\Users\madha\OneDrive\Desktop\DS\Churn-Prediction-JMAN\data\processed